/**
 * CE FICHIER EST GENERE. Ne pas l'editer a la main.
 * Source : public/assets/photos/registre.json
 * Regeneration : node scripts/genere-descriptions-photos.mjs
 *
 * La description de chaque photo, telle qu'elle a ete ecrite au registre.
 * Elle devient le texte alternatif de l'image : une photo posee sans
 * description est muette pour un lecteur d'ecran et pour un moteur.
 */

const DESCRIPTIONS: Record<string, string> = {
  "aero-cockpit-inspection-hangar.jpg": "Inspection du cockpit d'un avion léger en hangar",
  "aero-fuselage-serrage-lampe.jpg": "Serrage sur un panneau de fuselage à la lampe frontale",
  "aero-nacelle-moteur-technicien.jpg": "Technicien penché sur la nacelle d'un moteur d'avion",
  "aero-percage-aile-avion.jpg": "Technicien perçant l'aile d'un avion de ligne en hangar",
  "aero-reacteur-capot-combinaison.jpg": "Technicien en combinaison au capot d'un réacteur",
  "agro-atelier-inox-plan-large.jpg": "Atelier agroalimentaire inox en plan large",
  "agro-ihm-ligne-conditionnement-senior.jpg": "Technicien senior sur l'IHM d'une ligne de conditionnement",
  "agro-mains-vanne-sanitaire.jpg": "Mains réglant une vanne sanitaire inox au tournevis",
  "agro-panneau-vannes-nep.jpg": "Changement de circuit sur un panneau de vannes sanitaires",
  "agro-remplisseuse-cle-plate.jpg": "Intervention à la clé plate sur une remplisseuse rotative",
  "agro-technicienne-raccord-clamp.jpg": "Technicienne en charlotte contrôlant une tuyauterie de process inox",
  "automatisme-armoire-jeune-tablette.jpg": "Jeune technicien casqué, tablette en main devant une armoire d'automatisme",
  "automatisme-camera-vision-convoyeur.jpg": "Caméra de vision industrielle au-dessus d'un convoyeur",
  "automatisme-coffret-cartes-portable.jpg": "Technicien accroupi, portable branché sur un coffret de cartes de commande",
  "automobile-ligne-montage-binome.jpg": "Binôme sous une caisse sur une ligne de montage final",
  "chaudro-meulage-visiere.jpg": "Meulage d'un cordon de soudure sous visière de protection",
  "chaudro-presse-plieuse.jpg": "Chaudronnier réglant un pli sur presse plieuse",
  "chaudro-technicienne-plan-etabli.jpg": "Technicienne casquée lisant un plan dans un hall de chaudronnerie",
  "chimie-cuve-melange-flexible.jpg": "Technicien contrôlant une cuve de mélange, tablette en main",
  "chimie-piquage-manometre-gants.jpg": "Mains gantées réglant un piquage avec manomètre sur une cuve inox",
  "chimie-reacteurs-agites-passerelle.jpg": "Batterie de réacteurs agités vue depuis une passerelle",
  "chimie-technicienne-skid-vanne.jpg": "Technicienne réglant une vanne sur un skid d'instrumentation",
  "ciment-escalier-silo-ronde.jpg": "Ronde dans l'escalier d'une tour de silos",
  "ciment-inspection-binome-harnais.jpg": "Binôme en combinaison et harnais inspectant un équipement",
  "ciment-tambour-rotatif-silos.jpg": "Tambour rotatif à couronne dentée et silos",
  "ciment-vue-aerienne-usine.jpg": "Vue aérienne d'une cimenterie, tour de préchauffage et silos",
  "elec-armoire-pont-roulant-gilet.jpg": "Contrôle de l'armoire de commande d'un pont roulant",
  "elec-binome-coffret-chaufferie.jpg": "Binôme en diagnostic devant un coffret de commande en chaufferie",
  "elec-cablage-armoire-tournevis.jpg": "Électricien casqué et ganté au tournevis dans une armoire câblée",
  "elec-local-technicien-accroupi.jpg": "Technicien accroupi en local électrique, main sur le tableau",
  "elec-main-disjoncteurs-borniers.jpg": "Main manœuvrant des disjoncteurs au-dessus des borniers",
  "elec-mains-bornier-relais.jpg": "Mains serrant un bornier au tournevis dans une armoire dense",
  "elec-mesure-multimetre-faisceau.jpg": "Mesure au multimètre dans un faisceau de câbles industriel",
  "elec-multimetre-armoire-automatisme.jpg": "Dépannage électromécanique au multimètre dans une armoire",
  "elec-porte-armoire-voyants-sectionneurs.jpg": "Porte d'armoire avec voyants, boutons et sectionneurs cadenassables",
  "elec-salle-cellules-ht-ronde.jpg": "Ronde en salle de cellules HT/BT d'une centrale",
  "elec-schema-lampe-frontale.jpg": "Technicienne à lampe frontale lisant un schéma devant une armoire",
  "elec-senior-armoire-relais.jpg": "Technicien senior devant une armoire de relais ouverte, portable en main",
  "elec-tgbt-technicienne-tablette.jpg": "Technicienne en gilet haute visibilité contrôlant les voyants d'un TGBT",
  "elec-thermometre-infrarouge-armoire.jpg": "Contrôle de température au thermomètre infrarouge sur une armoire",
  "energie-bride-mat-eolienne.jpg": "Deux techniciens sur la bride boulonnée d'un mât d'éolienne",
  "energie-eolien-hauteur-harnais.jpg": "Technicien éolien en hauteur, harnais et longe",
  "energie-levage-eolienne-senior.jpg": "Technicien senior sous les élingues d'un levage d'éolienne",
  "energie-rack-canalisations-binome.jpg": "Binôme sous un rack de canalisations calorifugées",
  "energie-releve-pupitre-salle-commande.jpg": "Relevé de ronde devant un pupitre de salle de commande",
  "energie-rotor-turbine-vapeur.jpg": "Révision d'un rotor de turbine vapeur haute pression",
  "env-assemblage-carrosseries.jpg": "File de caisses de voitures rouges en cours d'habillage sur la ligne d'assemblage d'une usine automobile",
  "env-assemblage-chassis-automobile.jpg": "Deux opérateurs travaillant de part et d'autre d'une caisse en blanc maintenue sur son convoyeur de ligne",
  "env-automatician-maintenance.jpg": "Technicien casqué pilotant un bras robot depuis le boîtier de commande, derrière la grille de la cellule",
  "env-avion-en-maintenance.jpg": "Deux avions de ligne ouverts et entourés d'échafaudages dans un hangar de maintenance",
  "env-bras-robotiques-soudant-cadres-auto.jpg": "Bras robots orange alignés autour des caisses, sous le convoyeur aérien d'un atelier de carrosserie",
  "env-car-bodies-assembly-line.jpg": "Soubassement d'un véhicule vu en contre-plongée au-dessus de la ligne d'assemblage",
  "env-car-manufacturing-engine-assembly-on-automated.jpg": "Groupe motopropulseur avec son disque de frein posé sur un chariot de transfert motorisé, caisses suspendues au-dessus",
  "env-controle-qualite-femme.jpg": "Opératrice en charlotte et gants examinant une bouteille d'eau en sortie de soutireuse inox",
  "env-deux-hommes-au-travail-en-menuiserie.jpg": "Deux menuisiers comparant deux tasseaux devant une scie radiale dans un atelier bois",
  "env-deux-hommes-menuiserie.jpg": "Menuisier casqué sciant une planche à la scie égoïne, un collègue au travail sur l'établi derrière lui",
  "env-emballage-de-biscuits-en-usine.jpg": "Opérateurs en blouse et charlotte garnissant des boîtes de biscuits le long d'une table d'emballage",
  "env-entretien-avion-22-sept-2026.jpg": "Deux mécaniciens intervenant sous l'aile et le train d'un avion en hangar, caisse à outils et lampe au sol",
  "env-factory-worker-inspecting-food-canning-product.jpg": "Opératrice de dos surveillant le défilé des boîtes de conserve remplies de sauce sur la ligne de sertissage",
  "env-factory-worker-inspecting-robotic-arm-in-manuf.jpg": "Technicien en gilet haute visibilité inspectant le poignet d'un bras robot orange dans sa cellule grillagée",
  "env-femme-en-costume-sterile-industrie-pharmaceuti.jpg": "Opératrice en tenue stérile manœuvrant la vanne d'un réacteur inox en salle blanche",
  "env-femme-en-usine-moderne.jpg": "Opératrice en blouse de salle blanche postée le long d'une encartonneuse en fonctionnement",
  "env-femme-inspectant-des-bouteilles.jpg": "Technicienne en charlotte contrôlant une bouteille plastique au poste de soufflage d'une ligne d'embouteillage",
  "env-femmes-en-usine-21-sept-2026.jpg": "Deux techniciennes en blouse relevant des mesures sur ordinateur devant une ligne de bouteilles d'eau",
  "env-focused-young-man-working-on-electrical-wiring.jpg": "Gros plan d'un technicien en salopette intervenant à la pince sur un faisceau de fils colorés",
  "env-food-production-line-with-workers-in-protectiv.jpg": "Ligne de conserverie inox avec ses doseurs coniques, opératrices masquées en arrière-plan",
  "env-homme-inspectant-le-bois.jpg": "Opérateur casqué engageant un paquet de lattes de bois sur la table d'une machine de seconde transformation",
  "env-industrial-infrastructure-with-blue-sky-and-cl.jpg": "Colonnes, cheminées et racks de tuyauterie d'une raffinerie sous un ciel bleu nuageux",
  "env-industrial-worker-inspecting-canned-goods-on-a.jpg": "Main gantée d'un opérateur reprenant une boîte de conserve sur la sertisseuse en marche",
  "env-industrie-au-crepuscule-2.jpg": "Vue aérienne d'une raffinerie au couchant, bacs de stockage et racks de tuyauterie au premier plan",
  "env-industrie-au-crepuscule.jpg": "Colonnes et cheminées fumantes d'une usine chimique devant des collines, au crépuscule",
  "env-industrie-automobile.jpg": "Vue plongeante sur un atelier automobile, caisses sur convoyeur aérien et rangée de robots orange",
  "env-industrie-chimie-2.jpg": "Deux intervenants en gilet jaune et casque longeant une unité pétrochimique",
  "env-industrie-chimie-3.jpg": "Colonnes de distillation et bacs de stockage d'un complexe pétrochimique en bord de ville",
  "env-industrie-chimie.jpg": "Enchevêtrement de colonnes, de réservoirs et de cheminées fumantes d'un complexe chimique",
  "env-industrie-metallique-2.jpg": "Poche de coulée suspendue au pont roulant déversant du métal en fusion dans une gerbe d'étincelles",
  "env-industrie-metallique-21-sept-2026.jpg": "Halle d'aciérie éclairée par la flamme d'un four, machine de chargement engagée devant la gueule",
  "env-industrie-metallique-22-sept-2026-1.jpg": "Fondeur en tenue aluminisée surveillant le basculement d'une poche de coulée au-dessus du bain",
  "env-industrie-metallique-24-sept-2026.jpg": "Jet de métal en fusion coulant dans une lingotière au milieu d'une halle d'aciérie équipée de ponts roulants",
  "env-industrie-metallique.jpg": "Opérateur en tenue aluminisée posté devant la bouche enflammée d'un four, derrière une rambarde jaune",
  "env-industrie-mettalique-22-sept-2026.jpg": "Quatre fondeurs casqués et visière baissée travaillant la coulée à la barre devant un four de fonderie",
  "env-industrie-mettalique.jpg": "Fondeur en veste aluminisée guidant à bout de bras une poche de coulée qui déverse l'acier liquide",
  "env-industrie-paysage.jpg": "Vue aérienne d'un complexe sidérurgique, cheminée fumante, silos et galeries de convoyeurs",
  "env-industrie-pharmaceutique.jpg": "Ligne de conditionnement de flacons derrière une cloison vitrée, opérateur en blouse dans la salle attenante",
  "env-industrie.jpg": "Vue d'ensemble d'un complexe pétrochimique hérissé de colonnes de distillation et de cheminées fumantes",
  "env-infrastructure-usine-acier-avec-tuyaux.jpg": "Réseau de grosses conduites et vanne à volant au pied d'un haut fourneau d'aciérie",
  "env-ingenieurs-inspectant-site-industriel.jpg": "Deux intervenants en gilet haute visibilité parcourant une passerelle en caillebotis le long de conduites calorifugées",
  "env-inspection-auto-avec-equipe.jpg": "Échange autour d'un ordinateur portable sous le capot ouvert d'un véhicule dans un garage",
  "env-inspection-bras-robotiques.jpg": "Technicien accroupi, console de programmation en main, devant un bras robotisé orange et sa rangée d'armoires de commande",
  "env-inspection-de-bois-24-sept-2026.jpg": "Ouvrier casqué alignant de longues planches dans une halle de sciage inondée de lumière",
  "env-inspection-de-la-chaine-alimentaire.jpg": "Opérateur en blouse blanche et charlotte devant une ligne de convoyeurs inox d'un atelier agroalimentaire",
  "env-inspection-du-processus-d-embouteillage.jpg": "Deux opératrices contrôlant des bouteilles vertes sur une ligne d'embouteillage, tablette à la main",
  "env-inspection-equipement-fabrication.jpg": "Deux opérateurs en blouse et charlotte examinant une machine de conditionnement vue par-dessus ses mécanismes",
  "env-inspection-ligne-production-automatique.jpg": "Deux techniciens en gilet orange réglant un cobot sur un banc de production automatisé, tablette en main",
  "env-inspection-metal-22-sept-2026-1.jpg": "Opérateur juché sur un escabeau contrôlant d'énormes arbres d'acier usinés alignés dans une halle",
  "env-inspection-metal-22-sept-2026.jpg": "Technicien casqué inspectant les portées d'un arbre d'acier fraîchement usiné en atelier",
  "env-inspection-robot-arm-wiring.jpg": "Technicien relevant des mesures devant l'armoire de commande ouverte d'un robot, un collègue intervenant derrière",
  "env-inspection-robotique-21-sept-2026.jpg": "Technicien accroupi devant une armoire de commande ouverte, tablette en main, tandis qu'un collègue manipule le bras robotisé",
  "env-inspection-robotique-22-sept-2026.jpg": "Deux techniciens casqués contrôlant le poignet et la pince d'un robot industriel jaune",
  "env-maintenance-automaticien-2.jpg": "Technicien vissant une platine sur l'axe d'un robot orange, un second opérateur en arrière-plan",
  "env-maintenance-automaticien-3.jpg": "Technicien mesurant au multimètre dans une armoire électrique ouverte, au milieu de robots à l'arrêt",
  "env-maintenance-automaticien.jpg": "Deux techniciens en combinaison bleue examinant la pince d'un robot jaune dans un atelier de production",
  "env-maintenance-automatique-robotique.jpg": "Technicien accroupi serrant un raccord sur l'articulation d'un robot blanc à l'outil",
  "env-maintenance-automatique.jpg": "Trois techniciens mettant au point un robot jaune, tablette et ordinateur portable en main",
  "env-maintenance-worker-repairing-robot.jpg": "Technicien en gilet fluo intervenant bras levés sur un robot à l'intérieur de sa cage de sécurité",
  "env-man-smiles-at-a-bottling-plant-factory.jpg": "Opérateur en blouse et charlotte appuyé contre un convoyeur dans une usine d'embouteillage",
  "env-manipulation-metal-usine.jpg": "Ouvriers protégés par des écrans faciaux poussant des barres d'acier devant un four incandescent",
  "env-mecanicien-aeronautique.jpg": "Mécanicien en combinaison intervenant sur le fuselage d'un avion de ligne, réacteur ouvert derrière lui dans le hangar",
  "env-mechanic-inspecting-auto-parts-in-his-workshop.jpg": "Mécanicien ganté examinant une petite pièce devant son panneau de clés plates",
  "env-menuiserie-24-sept-2026.jpg": "Menuisier passant une pièce de bois sur une dégauchisseuse dans une halle de montage de modules",
  "env-menuiserie-circular-saw.jpg": "Opérateur casqué et protégé sciant une planche à la scie circulaire sur un établi",
  "env-menuiserie-industrie.jpg": "Charpentier penché perçant un madrier à la visseuse dans un atelier bois",
  "env-menuisier-avec-masque-sept-2026.jpg": "Menuisier masqué travaillant une pièce de bois près d'une perceuse à colonne dans son atelier",
  "env-menuisier-dans-l-atelier.jpg": "Serre-joints et pièces de bois en premier plan sur un établi, menuisier en arrière-plan dans l'atelier",
  "env-menuisier-utilisant-des-outils.jpg": "Charpentier coupant une pièce à la scie à onglet devant une ossature bois en extérieur",
  "env-moteur-d-avion-en-maintenance.jpg": "Réacteur déposé sur son berceau au milieu d'un atelier de maintenance",
  "env-oil-and-gas-petrochemical-industrial-oil-refin.jpg": "Raffinerie pétrochimique et ses colonnes de distillation sous un ciel de crépuscule",
  "env-operateur-de-metal-24-sept-2026.jpg": "Forgeron en tablier de cuir et masque devant sa presse, four incandescent et collègues en arrière-plan",
  "env-ouvrier-industriel-avec-ladle.jpg": "Ouvrier guidant à la perche une pièce incandescente sous une presse à volant dans une forge",
  "env-ouvrier-industriel-meulant-metal.jpg": "Ouvrier casqué meulant une pièce métallique dans une gerbe d'étincelles au milieu d'une grande halle",
  "env-ouvrier-metallurgiste-avec-metal-en-fusion.jpg": "Métallurgiste raclant à la perche un canal de coulée d'acier en fusion devant le four",
  "env-ouvrier-usine-coupe-metal-avec-scie-circulaire.jpg": "Ouvrier casqué tronçonnant au disque un essieu de véhicule dans un atelier sombre, gerbe d'étincelles au sol",
  "env-ouvrier-usine-metal-avec-etincelles.jpg": "Ouvrier tronçonnant une pièce de fonderie à la scie à disque dans une halle d'usine, pièces moulées empilées autour",
  "env-ouvrier-usine-metal.jpg": "Opérateur en bleu de travail surveillant une coulée d'acier en fusion depuis la passerelle d'une aciérie",
  "env-ouvriers-usine-allumant-four-sept-22.jpg": "Jet d'étincelles sous la poche d'un four de fusion en aciérie, opérateur en tenue aluminisée à l'écart",
  "env-photo-industrie-2.jpg": "Tours aéroréfrigérantes et cheminées d'une centrale thermique sous un ciel bleu",
  "env-photo-industrie-chimie.jpg": "Haut-fourneau et bâtiments d'un complexe sidérurgique, panaches de vapeur au-dessus d'un bassin de refroidissement",
  "env-photo-industrie-pharmaceutique.jpg": "Technicienne en tenue stérile refermant la trappe d'une cuve inox de mélange en salle blanche",
  "env-photo-industrie.jpg": "Réseau de tuyauteries calorifugées et ballons de vapeur sous la charpente d'une salle des machines",
  "env-photos-industrie-2.jpg": "Vue aérienne d'un complexe sidérurgique, convoyeur à bande vers le haut-fourneau et cheminées à perte de vue",
  "env-photos-industrie-3.jpg": "Colonnes de distillation et racks de tuyauterie d'une unité pétrochimique sous un ciel bleu",
  "env-photos-industrie-4.jpg": "Deux colonnes de distillation et leurs passerelles d'accès dans une raffinerie, ciel couvert",
  "env-photos-industrie-aeronautique.jpg": "Trois mécaniciens intervenant sur la voilure et le train d'un avion en hangar, réacteur déposé au premier plan",
  "env-photos-industrie-agro-alimentaire.jpg": "Rangée de cuves inox reliées par un collecteur de tuyauterie dans une salle de brassage",
  "env-photos-industrie-menuiserie-2.jpg": "Scie à onglet posée sur établi au premier plan d'un atelier de menuiserie où plusieurs ouvriers travaillent le bois",
  "env-photos-industrie-menuiserie-3.jpg": "Deux opérateurs casqués contrôlant une planche à la sortie d'une machine à bois à commande numérique",
  "env-photos-industrie-menuiserie.jpg": "Hall de stockage d'une scierie, madriers et bastaings empilés au sol avec un palonnier de levage",
  "env-photos-industrie-metallique.jpg": "Halle d'aciérie alignant poches et lingotières, deux ouvriers de dos sous un pont roulant",
  "env-photos-industrie-pharmaceutique.jpg": "Deux laborantins en blouse et charlotte renseignant une fiche près d'un évaporateur rotatif",
  "env-photos-industrie.jpg": "Technicien en gilet haute visibilité annotant des plans de nuit devant une usine pétrochimique illuminée",
  "env-photos-menuiserie-2.jpg": "Deux menuisiers casqués triant des planches de sapin sur un stock de bois scié",
  "env-photos-menuiserie.jpg": "Menuisier bridant une pièce de bois au serre-joint devant une scie à onglet, collègue portant des planches à l'arrière",
  "env-pommes-de-terre-sur-convoyeur.jpg": "Opérateur surveillant une calibreuse de pommes de terre sur une ligne de conditionnement",
  "env-professionnels-maintenance-aeronautique.jpg": "Deux mécaniciens travaillant sous la voilure d'un avion de ligne dans un hangar de maintenance",
  "env-professionnels-sur-machine-a-bois.jpg": "Deux opératrices conduisant une machine à bois avec aspiration dans un atelier de seconde transformation",
  "env-promenade-des-ingenieurs-a-la-raffinerie.jpg": "Deux techniciens en combinaison rouge marchant avec caisse à outils et tablette devant une raffinerie au crépuscule",
  "env-raffinerie-de-petrole-au-coucher-du-soleil.jpg": "Vue aérienne d'une raffinerie illuminée au crépuscule, colonnes, bacs de stockage et racks de tuyauterie",
  "env-raffinerie-de-petrole-bangkok.jpg": "Usine pétrochimique éclairée de nuit au bord d'un fleuve, réservoirs et racks de tuyauterie",
  "env-reparation-moteur-aeronautique.jpg": "Deux mécaniciens en combinaison bleue inspectant un réacteur capot ouvert sous l'aile d'un avion en hangar",
  "env-reparation-moteur-avion.jpg": "Vue verticale d'un hangar de maintenance, deux mécaniciens de part et d'autre d'un réacteur capot ouvert",
  "env-reparation-moteur-jet-hangar.jpg": "Quatre mécaniciens autour d'un réacteur déposé sur son chariot dans un hangar, avion de ligne à côté",
  "env-robot-industriel-2026.jpg": "Technicien pilotant un bras robotisé au pupitre d'apprentissage, collègue sur tablette derrière la grille de sécurité",
  "env-robotic-arms-welding-car-frames.jpg": "Bras robotisés orange manipulant des pièces de carrosserie sur une ligne d'assemblage automobile",
  "env-scie-a-ruban-industrielle.jpg": "Grande scie à ruban à volant dans une scierie, piles de planches et palettes tout autour",
  "env-scientist-in-pharmaceutical-lab.jpg": "Opératrice en tenue stérile intervenant sur la trappe d'un réacteur inox de production en salle blanche",
  "env-structures-industrielles-au-coucher-du-soleil.jpg": "Silhouettes de silos et d'élévateurs industriels au coucher du soleil, ville en arrière-plan",
  "env-structures-industrielles-contre-ciel-nuageux.jpg": "Colonnes, gaines et passerelles d'une unité pétrochimique se détachant sur un ciel bleu nuageux",
  "env-technician-examining-jet-engine.jpg": "Technicien réglant les circuits et raccords sous la cellule d'un aéronef en hangar",
  "env-technician-inspecting-electrical-panel-in-a-fa.jpg": "Technicien en veste haute visibilité accroupi devant une armoire électrique ouverte, bornes et fils apparents, dans un atelier",
  "env-technician-inspecting-fiber-optics.jpg": "Technicien agenouillé devant une baie de brassage, pince à dénuder en main, au milieu des jarretières optiques et cuivre",
  "env-technician-inspecting-power-grid-equipment-in-.jpg": "Technicien en gilet rouge et casque jaune vérifiant une rangée de coffrets électriques dans un local de distribution",
  "env-technician-maintenance-10.jpg": "Opérateur penché dans une carrosserie démontée pour raccorder le faisceau électrique du véhicule",
  "env-technician-maintenance-11.jpg": "Mécanicien en salopette manipulant une grosse pièce circulaire sur un poids lourd blanc dans un atelier de garage",
  "env-technician-maintenance-12.jpg": "Technicien en casque jaune serrant un assemblage à la clé à cliquet au-dessus de sa tête dans une halle de production",
  "env-technician-maintenance-13.jpg": "Deux techniciens en bleu de travail intervenant à la clé sur la tête articulée d'une grosse machine en atelier",
  "env-technician-maintenance-2.jpg": "Opérateur en combinaison bleue actionnant le pupitre d'une machine-outil verte dans un atelier d'usinage",
  "env-technician-maintenance-3.jpg": "Technicien en casque jaune contrôlant un outillage suspendu à la charpente d'une halle de production",
  "env-technician-maintenance-4.jpg": "Technicien en combinaison rouge inspectant à la lampe le soubassement d'une rame sur voie d'atelier",
  "env-technician-maintenance-5.jpg": "Technicien accroupi mesurant au multimètre dans une armoire d'automatisme ouverte, bras robotisé en arrière-plan",
  "env-technician-maintenance-6.jpg": "Technicien agenouillé sous un réseau de tuyauteries pour manœuvrer une vanne dans une salle de machines",
  "env-technician-maintenance-7.jpg": "Technicien en casque bleu penché dans une baie informatique ouverte pour vérifier le câblage",
  "env-technician-maintenance-8.jpg": "Réparateur en gants orange intervenant sur les entrailles d'une machine à café, multimètre branché sur l'établi",
  "env-technician-maintenance-9.jpg": "Mains gantées testant à la pointe de touche le bornier d'un groupe extérieur de climatisation",
  "env-technician-maintenance-blue-truck-engine.jpg": "Technicien à la clé à cliquet sur le flanc d'une machine bleue garnie de flexibles, dans un atelier",
  "env-technician-maintenance-jet-engine.jpg": "Mécanicien aéronautique intervenant sur un réacteur capot ouvert dans un hangar de maintenance",
  "env-technician-maintenance-repairs.jpg": "Technicien en gilet jaune resserrant une pièce sur un gros équipement sombre dans un atelier peu éclairé",
  "env-technician-maintenance-robot-arm.jpg": "Deux techniciens intervenant à la clé sur des bras robotisés orange alignés dans un atelier",
  "env-technician-maintenance-robotic-arm.jpg": "Technicien tablette en main inspectant le poignet d'un robot industriel blanc en atelier",
  "env-technician-maintenance.jpg": "Technicien contrôlant au multimètre le câblage d'une armoire de commande ouverte",
  "env-technician-with-robotic-arm.jpg": "Technicien en casque blanc ajustant la carte électronique montée sur le bras d'un robot blanc",
  "env-technicien-en-costume-de-nettoyage-industrie-p.jpg": "Opérateur en combinaison intégrale et masque devant des skids inox de procédé dans une salle blanche",
  "env-technicien-maintenance-2.jpg": "Technicien en haute visibilité câblant une armoire électrique ouverte au pied d'une cellule robotisée",
  "env-technicien-maintenance-aeronautique.jpg": "Technicien éclairant au frontal le train d'atterrissage et ses flexibles sous un avion",
  "env-technicien-maintenance-cafe-23-sept-2026.jpg": "Gros plan de mains gantées remontant le mécanisme interne d'une machine à café, courroie et faisceau apparents",
  "env-technicien-maintenance-photo.jpg": "Technicien bras croisés au milieu des gaines et tuyauteries d'un local technique",
  "env-technicien-maintenance-serveur.jpg": "Technicien raccordant les câbles réseau dans une armoire de brassage ouverte",
  "env-technicien-maintenance.jpg": "Technicien en gilet vert raccordant les câbles de l'outil terminal d'un robot industriel",
  "env-techniciens-semiconducteurs.jpg": "Opérateur en combinaison de salle blanche contrôlant une plaquette au-dessus d'une ligne de conditionnement de flacons",
  "env-travailleuse-usine-agroalimentaire.jpg": "Opératrice en blouse jaune relevant des données sur tablette le long d'un convoyeur de boîtes de conserve",
  "env-usine-aeronautique-22-sept-2026.jpg": "Halle d'assemblage aéronautique alignant des fuselages en cours de montage sous une verrière",
  "env-usine-metallique.jpg": "Intérieur d'une aciérie, lueur orange du four et charpente métallique dans la poussière",
  "env-workers-inspecting-large-vats-in-a-manufacturi.jpg": "Deux opérateurs en blanc penchés sur des cuves de fromagerie dans un atelier carrelé",
  "equipe-consignes-atelier-casques.jpg": "Consignes données à une équipe casquée en atelier",
  "equipe-transmission-senior-jeune.jpg": "Un ancien explique des pièces de machine à un jeune technicien",
  "hydrau-centrale-hydraulique-technicien.jpg": "Intervention sur une centrale hydraulique",
  "hydrau-presse-pupitre-manometre.jpg": "Presse hydraulique avec plateau, manomètre et pupitre",
  "hydrau-verin-tige-chromee.jpg": "Vérin monté sur machine, tige chromée et raccord de flexible",
  "il-automaticien-ajustant-bras-robotique-1600.jpg": "Technicienne en casque et gilet haute visibilité ajustant la pince en bout de bras d'un robot industriel",
  "il-automaticien-avec-robot-arme-mar-19-2026-1600.jpg": "Technicien bras croisés devant une cellule robotisée grillagée équipée d'une pince de soudage par points",
  "il-automaticien-dans-usine-moderne-jan-7-2026-160.jpg": "Technicien posant entre un tour à commande numérique et un robot jaune de chargement dans un atelier d'usinage",
  "il-automaticien-utilisant-un-bras-robotique-1600.jpg": "Technicienne assise à un poste d'essai, programmant depuis un ordinateur portable un petit bras robotique de table",
  "il-automaticien-verifiant-photo-jan-6-2026-1600.jpg": "Technicienne tenant un pupitre d'apprentissage devant un bras robotique, armoire de commande à boutons en arrière-plan",
  "il-automation-female-engineer-with-tablet-for-pro.jpg": "Ingénieure en veste de tailleur et casque de chantier, tablette à la main, devant des robots industriels orange",
  "il-checking-heavy-equipment-at-modern-plant.jpg": "Technicien contrôlant le faisceau et les injecteurs d'un gros moteur diesel bleu",
  "il-chimie-colonnes-raffinerie-nuit.jpg": "Détail des colonnes de distillation d'une raffinerie éclairée de nuit",
  "il-cimenterie-de-nuit-mars-25-2026-1600.jpg": "Cimenterie portuaire éclairée au crépuscule, tour de préchauffage et silos au bord de l'eau avec navires à quai",
  "il-concept-usine-intelligente-2026-1600.jpg": "Technicienne câblant un banc d'automatisme, borniers, automate et boutons poussoirs, un robot en arrière-plan",
  "il-detail-raffinerie-nuit-mars-17-2026-1600.jpg": "Colonnes de distillation et racks de tuyauterie d'une raffinerie éclairés en pleine nuit",
  "il-engineer-check-and-control-automation-robot-ar.jpg": "Technicien en combinaison orange réglant la torche de soudage montée en bout d'un bras robotisé",
  "il-equipement-et-pipeline-raffinerie-2026-1600.jpg": "Rack de tuyauterie et bacs de stockage d'un site pétrochimique vus en contre-plongée à contre-jour",
  "il-female-engineer-inspecting-machinery-in-indust.jpg": "Technicienne carnet et stylo en main inspectant l'embase d'un bras robotique dans une halle d'atelier",
  "il-female-engineers-working-on-robotics-in-indust.jpg": "Technicienne en visière de protection derrière un bras robotique blanc et un banc d'essai câblé",
  "il-female-technician-inspects-industrial-equipmen.jpg": "Technicienne mesurant à la pince multimètre dans l'armoire de commande ouverte d'un robot",
  "il-femme-confiante-en-milieu-industriel-mar-24-20.jpg": "Technicienne avec radio portative devant une cellule d'armoire électrique de distribution",
  "il-femme-en-tenue-professionnelle-pres-d-un-bras-.jpg": "Femme en tailleur levant l'index près d'un bras robotique blanc en arrière-plan flou",
  "il-femme-inspectant-bras-robotique-2026-1600.jpg": "Technicienne ordinateur portable ouvert devant une cellule robotisée, deux collègues en discussion derrière elle",
  "il-femme-souriante-avec-casque-et-lunettes-de-sec.jpg": "Technicienne en casque et lunettes tenant un pupitre de commande à arrêt d'urgence près d'un bras robotique",
  "il-hydrau-verin-godet-engin.jpg": "Technicien intervenant sur le vérin et l'axe de godet d'un engin de chantier",
  "il-industrie-paysage-au-coucher-de-soleil-1600.jpg": "Aciérie au bord de l'eau au crépuscule, hauts fourneaux et cheminées fumantes",
  "il-industrie-photo-jan-5-2026-1600.jpg": "Grosses conduites de gaz et passerelles rouillées d'une vieille aciérie vues en contre-plongée",
  "il-ingenieur-verifiant-train-electrique-jan-7-202.jpg": "Deux techniciens inspectant des bogies ferroviaires posés au sol dans un atelier équipé de ponts roulants",
  "il-inspection-de-terrain-en-securite-mars-2026-16.jpg": "Deux techniciens en tenue haute visibilité consultant une tablette devant une raffinerie au crépuscule",
  "il-interieur-de-chantier-naval-24-mars-2026-1600.jpg": "Halle de construction métallique, poutres et tôles alignées au sol, plateau automoteur jaune sous les ponts roulants",
  "il-man-working-with-machinery-in-a-factory.jpg": "Technicien réglant les commandes d'un tour conventionnel ancien dans un atelier d'usinage",
  "il-man-works-with-robotic-arm-in-factory.jpg": "Technicien observant une préhension à ventouses montée sur un bras collaboratif, flexibles pneumatiques apparents",
  "il-mechanic-working-in-warehouse-2.jpg": "Technicien en salopette choisissant un outil coupant sur un rayonnage de magasin d'atelier d'usinage",
  "il-metal-siderurgie-bord-d-eau-couchant.jpg": "Usine sidérurgique en bord d'eau au coucher du soleil",
  "il-photo-industrie-japon-jan-9-2026-1600.jpg": "Complexe pétrochimique vieillissant, colonnes, charpentes et tuyauterie rouillées sous ciel bleu",
  "il-photo-industrie-raffinerie-petrole-mars-2026-1.jpg": "Vue aérienne d'une raffinerie éclairée au coucher du soleil, bacs de stockage et torchère allumée",
  "il-photo-usine-ciment-16-mars-2026-1600.jpg": "Cimenterie en hiver, tour de préchauffage, silos et grues à tour derrière un champ enneigé",
  "il-photo-usine-ciment-mars-17-2026-1600.jpg": "Silhouette d'une cimenterie au soleil rasant, tour de préchauffage, convoyeur incliné et grues à tour",
  "il-pipes-et-structures-raffinerie-2026-1600.jpg": "Contre-plongée sur un silo, des convoyeurs capotés et de grosses conduites d'une installation de vrac",
  "il-portrait-of-engineer-or-technician-worker-woma.jpg": "Technicienne avec tablette en ronde dans une galerie de tuyauterie calorifugée équipée de vannes motorisées bleues",
  "il-portrait-of-engineer-train-inspect-the-train-s-2.jpg": "Mécanicien manœuvrant un volant de vanne en laiton dans la cabine d'une locomotive à vapeur, manomètres et robinetterie au-dessus de lui",
  "il-portrait-of-engineer-train-inspect-the-train-s.jpg": "Technicienne en combinaison rouge actionnant une manette de commande dans la cabine d'une locomotive",
  "il-raffinerie-industrielle-au-crepuscule-1600.jpg": "Raffinerie pétrochimique vue de l'extérieur en plein jour, colonnes de distillation, cheminées et réseaux de tuyauterie",
  "il-silos-agricoles-exterieur.jpg": "Batterie de silos à grain métalliques vue en contre-plongée, avec passerelles et convoyeurs de transfert",
  "il-soudure-poste-masque-releve.jpg": "Soudeur masque relevé devant son poste à souder et ses bouteilles de gaz",
  "il-technician-using-control-panel-in-industrial-f.jpg": "Régleur programmant le pupitre à commande numérique d'une machine-outil en atelier",
  "il-technicien-maintenance-2.jpg": "Technicien accroupi devant un panneau d'outillage isolé, dans un local de commande bordé d'armoires électriques",
  "il-technicien-maintenance-3.jpg": "Technicienne tenant le poignet d'un bras robotisé, boîtier de commande dans l'autre main",
  "il-technicien-maintenance-4.jpg": "Technicien bras croisés entre des colonnes de tuyauterie calorifugée et des chemins de câbles d'un local technique",
  "il-technicien-maintenance-5.jpg": "Technicien à la porte vitrée d'une machine automatisée équipée de vérins et de flexibles",
  "il-technicien-maintenance-6.jpg": "Technicien assis tablette en main devant une armoire électrique ouverte, à côté d'un robot industriel orange",
  "il-technicien-maintenance-7.jpg": "Technicien en combinaison rouge parlant dans une radio portative près d'un palier de machine",
  "il-technicien-maintenance-8.jpg": "Technicien accroupi actionnant le volant d'avance d'un tour dans un atelier de mécanique",
  "il-technicien-maintenance-air-conditionne-1600.jpg": "Technicienne frigoriste nettoyant au pinceau un groupe de climatisation extérieur ouvert, compresseur et boîtier électrique apparents",
  "il-technicien-maintenance-au-travail-jan-9-2026-1.jpg": "Technicienne en combinaison rouge communiquant par radio sous une machine, ressort de suspension au premier plan",
  "il-technicien-maintenance-avec-cle-1600.jpg": "Technicien posant avec une clé à molette dans un dépôt ferroviaire, locomotive sur fosse derrière lui",
  "il-technicien-maintenance-avec-robot-1600.jpg": "Technicienne accroupie près d'une armoire de commande et d'un robot industriel encore emballé sous film",
  "il-technicien-maintenance-avion-jan-9-2026-1600.jpg": "Technicien éclairant à la lampe le train d'atterrissage d'un aéronef, vérins et flexibles hydrauliques au-dessus de lui",
  "il-technicien-maintenance-camion-1600.jpg": "Mécanicien poids lourd sous la cabine basculée d'un camion, radiateur et circuits de refroidissement dégagés",
  "il-technicien-maintenance-en-securite-mar-23-2026-2.jpg": "Portrait en pied d'un technicien bras croisés dans une cellule robotisée, bras robot et armoire de câblage derrière lui",
  "il-technicien-maintenance-en-usine-1600.jpg": "Technicien accroupi intervenant sur les borniers d'une armoire électrique ouverte au pied d'une machine d'atelier",
  "il-technicien-maintenance-femme-1600.jpg": "Technicienne gantée intervenant sur un organe de machine en atelier, vue rapprochée",
  "il-technicien-maintenance-inspectant-bras-robotiq.jpg": "Technicien levant les yeux vers le bras d'un robot industriel en cellule de production",
  "il-technicien-maintenance-inspectant-equipement-j.jpg": "Automaticien portable sur les genoux, connecté à une armoire d'automate ouverte, robot rouge en arrière-plan",
  "il-technicien-maintenance-inspecte-equipement-ind.jpg": "Technicien accroupi entre des ballons tampons et un réseau de tuyauterie sur une terrasse technique, radio à la main",
  "il-technicien-maintenance-jan-09-2026-1600.jpg": "Technicien intervenant au tournevis sur le groupe hydraulique encrassé d'un engin, filtre et flexibles apparents",
  "il-technicien-maintenance-jan-6-2026-1600.jpg": "Technicien examinant une carte électronique de puissance déposée, tournevis en main, devant la machine d'origine",
  "il-technicien-maintenance-jan-7-2026-1600.jpg": "Technicien en ronde avec tablette entre les gaines et tuyauteries calorifugées d'une installation technique en toiture",
  "il-technicien-maintenance-jan-9-2026-1-1600.jpg": "Mécanicien automobile tenant une clé à chocs sous un véhicule tout-terrain levé sur pont élévateur",
  "il-technicien-maintenance-jan-9-2026-1600.jpg": "Technicienne la main sur l'outil en bout de bras d'un robot industriel orange",
  "il-technicien-maintenance-photo-1-1600.jpg": "Technicienne manipulant une jarretière de fibre optique devant des baies de brassage câblées",
  "il-technicien-maintenance-photo-10-1600.jpg": "Technicienne bras croisés tenant une grosse clé plate devant un engin lourd dans un atelier",
  "il-technicien-maintenance-photo-11-1600.jpg": "Technicienne gantée posant la main sur une pièce de machine en atelier, vue rapprochée",
  "il-technicien-maintenance-photo-12-1600.jpg": "Technicien casqué, lunettes et casque antibruit relevé, cadré derrière des câbles au premier plan",
  "il-technicien-maintenance-photo-13-1600.jpg": "Technicien tenant son casque sous le bras devant un pupitre mural d'appareils de mesure et d'enregistreurs en salle de contrôle",
  "il-technicien-maintenance-photo-14-1600.jpg": "Technicien accroupi devant une armoire ouverte, pointes de touche sur un bornier d'automate, multimètre posé sur le genou",
  "il-technicien-maintenance-photo-15-1600.jpg": "Technicienne gantée intervenant sur l'axe d'un bras robotisé orange en atelier",
  "il-technicien-maintenance-photo-16-800.jpg": "Portrait en pied d'une technicienne en combinaison, casque jaune à coquilles antibruit, dans une halle de production",
  "il-technicien-maintenance-photo-1600.jpg": "Technicien gantés travaillant sur une grande couronne dentée d'un ensemble mécanique démonté en atelier, un collègue en arrière-plan",
  "il-technicien-maintenance-photo-17-1600.jpg": "Technicien en vareuse debout devant un tableau d'instruments et de compteurs en salle de commande",
  "il-technicien-maintenance-photo-18-1600.jpg": "Technicienne en veste haute visibilité réglant la commande d'une machine-outil sous la halle d'atelier",
  "il-technicien-maintenance-photo-19-1600.jpg": "Technicienne ajustant la torche de soudage en bout d'un robot, boîtier de commande portatif posé sur la table",
  "il-technicien-maintenance-photo-2-1600.jpg": "Technicienne casquée manœuvrant le volant d'une machine-outil dans un atelier sombre",
  "il-technicien-maintenance-photo-20-1600.jpg": "Technicien bras croisés devant le pupitre de commande numérique d'une machine-outil dans un atelier",
  "il-technicien-maintenance-photo-21-1600.jpg": "Technicienne tablette en main devant une armoire de puissance ouverte, bras robotisé et presse en arrière-plan",
  "il-technicien-maintenance-photo-22-1600.jpg": "Mécanicien à lampe frontale, clé à molette sous le bras, devant un réacteur d'avion capots ouverts dans un hangar",
  "il-technicien-maintenance-photo-23-1600.jpg": "Technicien casqué manœuvrant la manette d'une machine d'atelier au milieu des tuyauteries rouges",
  "il-technicien-maintenance-photo-24-1600.jpg": "Technicien expérimenté inspectant un grand plateau d'embrayage boulonné, aidé par les mains d'un collègue",
  "il-technicien-maintenance-photo-3-1600.jpg": "Technicien en bleu de travail vissant au tournevis sur le carter rouge d'une machine en atelier",
  "il-technicien-maintenance-photo-4-1600.jpg": "Mécanicienne penchée sur le moteur d'une voiture capot ouvert dans un garage",
  "il-technicien-maintenance-photo-5-1600.jpg": "Technicien accroupi, multimètre en main, mesurant dans une armoire de variateurs et de borniers",
  "il-technicien-maintenance-photo-6-1600.jpg": "Technicienne en veste haute visibilité contrôlant une rangée de motoréducteurs en salle des machines",
  "il-technicien-maintenance-photo-7-1600.jpg": "Technicien à coquilles antibruit réglant la rampe d'injecteurs d'un gros moteur diesel en salle des machines",
  "il-technicien-maintenance-photo-8-1600.jpg": "Technicienne mesurant à la pointe de touche dans la boîte à bornes d'un moteur électrique",
  "il-technicien-maintenance-photo-9-1600.jpg": "Technicienne en gilet orange contrôlant l'outil monté en bout d'un bras robotisé",
  "il-technicien-maintenance-photo-jan-5-2026-1600.jpg": "Technicienne en combinaison bleue prenant une clé sur le panneau d'outillage mural d'un atelier",
  "il-technicien-maintenance-photo-jan-7-2026-1-1600.jpg": "Technicien réglant l'outil d'une perceuse à colonne équipée de sa buse d'arrosage",
  "il-technicien-maintenance-photo-jan-7-2026-2-1600.jpg": "Technicien pince ampèremétrique en main devant une armoire de commande ouverte sur ses cartes et son câblage",
  "il-technicien-maintenance-photo-jan-8-2026-1-1600.jpg": "Technicien remplaçant le tube contact de la torche de soudage d'un robot en atelier",
  "il-technicien-maintenance-photo-jan-8-2026-1600.jpg": "Technicien en gilet orange intervenant sur le faisceau et les conduites d'injection d'un moteur diesel bleu",
  "il-technicien-maintenance-photo-jan-8-2026-2-1600.jpg": "Technicienne intervenant à la pince sur le câblage d'une armoire de commande ventilée, robots en arrière-plan",
  "il-technicien-maintenance-photo-jan-8-2026-3-1600.jpg": "Technicien à coquilles antibruit pianotant sur le pupitre d'un coffret de commande en salle des machines, tuyauteries au plafond",
  "il-technicien-maintenance-photo-jan-9-2026-1-1600.jpg": "Technicienne contrôlant un banc automatisé équipé de vérins et de capteurs dans un atelier clair",
  "il-technicien-maintenance-photo-jan-9-2026-1600.jpg": "Technicien bras croisés devant une armoire électrique de distribution en local technique",
  "il-technicien-maintenance-photo-jan-9-2026-2-1600.jpg": "Technicien inspectant les vérins chromés et les flexibles d'une presse hydraulique en atelier",
  "il-technicien-maintenance-photo-jan-9-2026-3-1600.jpg": "Opératrice en bandana et salopette, gants de travail, penchée sur une machine dans un atelier industriel",
  "il-technicien-maintenance-photo-mar-18-2026-1-160.jpg": "Technicien en casque blanc et gilet orange inspectant de près une machine garnie de flexibles et de vérins",
  "il-technicien-maintenance-photo-mar-18-2026-1600.jpg": "Technicien en casque jaune intervenant bras levés sur des capteurs et des vérins en partie haute d'une machine",
  "il-technicien-maintenance-photo-mar-19-2026-1-160.jpg": "Jeune opérateur en casque orange et gilet haute visibilité posant bras croisés devant une presse mécanique rouge à volant",
  "il-technicien-maintenance-photo-mar-19-2026-1600.jpg": "Technicien en combinaison orange et casque antibruit dans un atelier d'usinage équipé d'un étau et de machines",
  "il-technicien-maintenance-photo-mar-24-2026-1600.jpg": "Électricien à lampe frontale démêlant un faisceau de fils sous une armoire en cours de dépose",
  "il-technicien-maintenance-photo-mar-25-2026-1-160.jpg": "Technicienne en casque blanc et gilet haute visibilité assise devant un pupitre de commande dans un atelier sombre",
  "il-technicien-maintenance-photo-mar-25-2026-1600.jpg": "Technicien en casque et protections auditives souriant près d'une machine, devant une paroi métallique rivetée",
  "il-technicien-maintenance-photo-mars-24-2026-1-16.jpg": "Technicienne en casque bleu inspectant l'intérieur d'un corps de machine en fonte posé dans un atelier",
  "il-technicien-maintenance-photo.jpg": "Portrait d'un technicien en veste de travail devant les coffrets électriques muraux d'un local technique",
  "il-technicien-maintenance-portrait-1-1600.jpg": "Technicien en casque blanc posant devant une ligne de production automatisée à vérins et armoire de commande",
  "il-technicien-maintenance-portrait-1600.jpg": "Soudeur masque relevé, torche en main, dans un atelier de soudage équipé de postes et de bras d'aspiration",
  "il-technicien-maintenance-portrait-jan-9-2026-160.jpg": "Technicien en casque bleu et salopette souriant dans un atelier de machines-outils, pupitre à voyants en arrière-plan",
  "il-technicien-maintenance-portrait-mars-2026-1600.jpg": "Mécanicien en salopette bras croisés devant son armoire à outils garnie de clés et de douilles",
  "il-technicien-maintenance-robot-industriel-jan-7-.jpg": "Technicien en casque jaune intervenant sur le préhenseur en bout de bras d'un robot industriel rouge",
  "il-technicien-maintenance-robot-industriel-mar-16.jpg": "Technicienne, presse-papiers en main, inspectant le bras d'un robot industriel dans une halle de production",
  "il-technicien-maintenance-robot-soudure-mar-24-20.jpg": "Technicien tenant un boîtier de programmation devant la torche de soudage portée par un robot",
  "il-technicien-maintenance-robotique-mar-17-2026-1.jpg": "Technicien en casque blanc ajustant l'outil en bout de bras d'un robot industriel bleu",
  "il-technicien-maintenance-robotique-mar-18-2026-1.jpg": "Technicien en casque blanc levant les yeux vers une machine suspendue dans une halle de production vitrée",
  "il-technicien-maintenance-selectionnant-outils-ja.jpg": "Technicien choisissant une douille dans le tiroir de sa servante à outils, cliquet en main",
  "il-technicien-maintenance-sur-pipeline-1600.jpg": "Technicien en casque jaune manoeuvrant la vanne d'un collecteur de tuyauteries à brides équipé d'un manomètre",
  "il-technicien-maintenance.jpg": "Technicienne en combinaison rouge éclairant à la lampe le dessous d'une machine de production pour l'inspecter",
  "il-technicienne-mecanique-photo-avril-2026-1600.jpg": "Mécanicienne souriante, cliquet en main, devant sa servante à outils dans un garage automobile à pont élévateur",
  "il-usine-chimique-nuit-mars-09-2026-1600.jpg": "Installation pétrochimique éclairée à la tombée de la nuit, colonnes, passerelles et réseaux de tuyauteries",
  "il-usine-de-ciment-vue-aerienne-1600.jpg": "Silos et convoyeurs inclinés d'une installation cimentière au coucher du soleil, surmontés d'une grue à tour",
  "il-usine-kawasaki-jan-11-2026-1600.jpg": "Raffinerie pétrochimique vue depuis les toits voisins, colonnes de distillation, tuyauteries et cheminées",
  "il-usines-a-yokkaichi-mars-24-2026-1600.jpg": "Complexe pétrochimique illuminé au crépuscule en bord de mer, cheminées fumantes, torchère et sphères de stockage",
  "il-vue-aerienne-usine-ciment-mars-16-2026-1600.jpg": "Cimenterie vue de haut, tour de préchauffage en béton, bâtiments de broyage et grues à tour",
  "il-young-african-american-worker-of-industrial-pl.jpg": "Technicien en casque blanc intervenant sur le faisceau et les accessoires d'un gros moteur thermique en atelier",
  "levage-montage-poteau-charpente.jpg": "Mise à l'aplomb d'un poteau de charpente métallique",
  "levage-pont-roulant-hall-acier.jpg": "Opérateur casqué guidant une charge au pont roulant",
  "levage-portique-tubes-exterieur.jpg": "Portique de levage déplaçant un fagot de tubes en parc extérieur",
  "logistique-ihm-convoyeur-bacs.jpg": "Pilotage tactile d'un convoyeur à bacs en intralogistique",
  "meca-cle-bride-carter.jpg": "Mains gantées serrant la bride d'un carter de réducteur",
  "meca-graissage-couronne-engin.jpg": "Graissage à la pompe d'une couronne de machine lourde",
  "meca-jeune-presse-volant.jpg": "Jeune technicien casqué sur une presse mécanique à volant",
  "meca-moteur-palan-depose.jpg": "Moteur électrique suspendu au palan pour dépose en atelier",
  "meca-pied-a-coulisse-fraiseuse.jpg": "Contrôle au pied à coulisse sur une perceuse-fraiseuse",
  "meca-presses-volants-technicienne.jpg": "Technicienne auditant une rangée de presses mécaniques à volant",
  "meca-reducteur-ouvert-plongee.jpg": "Vue en plongée d'un réducteur ouvert sur l'établi",
  "meca-reducteur-pont-roulant.jpg": "Remontage d'un motoréducteur suspendu au pont roulant",
  "meca-senior-rouleuse-combinaison.jpg": "Technicien senior accroupi sur une rouleuse à cylindres",
  "meca-technicienne-cle-machine.jpg": "Technicienne serrant à la clé sur une machine en hall industriel",
  "meca-technicienne-parc-moteurs.jpg": "Technicienne inspectant un parc de moteurs électriques",
  "meca-tour-conventionnel-senior.jpg": "Tourneur expérimenté sur un tour conventionnel",
  "menuiserie-centre-usinage-soufflette.jpg": "Opérateur ganté nettoyant un centre d'usinage bois",
  "menuiserie-cnc-pupitre-casque.jpg": "Technicien casqué pilotant une CNC à panneaux",
  "menuiserie-passerelle-usine-bois.jpg": "Technicien sur une passerelle dominant une usine du bois",
  "menuiserie-robot-panneaux.jpg": "Robot manipulant des panneaux en menuiserie industrielle",
  "menuiserie-scie-panneaux-epi.jpg": "Opérateur casqué sur une scie à panneaux industrielle",
  "metal-fonderie-coulee.jpg": "Fondeur en tenue aluminisée face à une coulée de métal",
  "metal-four-arc-acierie.jpg": "Four à arc électrique d'aciérie en plan large",
  "metal-technicienne-bobines-acier.jpg": "Technicienne contrôlant un stock de bobines d'acier",
  "nucleaire-salle-commande-centrale.jpg": "Salle de commande de centrale, ingénieur senior de dos",
  "nucleaire-tour-aerorefrigerante.jpg": "Tour aéroréfrigérante et panache de vapeur",
  "pharma-blistereuse-mecanisme.jpg": "Mécanisme d'une blistereuse pharmaceutique en gros plan",
  "pharma-cuves-process-passerelle.jpg": "Opérateur entre des cuves de process pharmaceutiques",
  "pharma-isolateur-salle-propre.jpg": "Opérateur en salle propre devant un isolateur à gants",
  "pharma-rouleaux-reglage-panoramique.jpg": "Réglage des rouleaux d'une machine pharmaceutique en zone stérile",
  "pharma-technicienne-machine-comprimes.jpg": "Technicienne en zone stérile réglant une machine à comprimés",
  "pneu-cle-bloc-distribution.jpg": "Serrage à la clé d'un raccord sur un bloc de distribution pneumatique",
  "pneu-pince-axe-lineaire.jpg": "Pince pneumatique sur axe linéaire et chaîne porte-câbles",
  "robot-atelier-ferrage-plongee.jpg": "Atelier de ferrage automobile robotisé, vue en plongée",
  "robot-cellule-soudure-inspection.jpg": "Inspection de la pince d'un robot de soudure au cœur de la cellule",
  "robot-cellules-grillagees.jpg": "Cellules robotisées derrière grillage de sécurité",
  "robot-cobot-technicienne.jpg": "Technicienne intervenant sur un cobot, pupitre en main",
  "robot-multimetre-cablage-robot.jpg": "Test au multimètre du câblage d'un robot industriel",
  "robot-palettisation-tablette.jpg": "Îlot de palettisation robotisé suivi sur tablette",
  "robot-palettiseur-fin-de-ligne.jpg": "Robot palettiseur en fin de ligne derrière clôture",
  "robot-palettiseur-sacs-poudre.jpg": "Robot palettiseur empilant des sacs de poudre",
  "robot-pince-reparation-etabli.jpg": "Réparation d'une pince de robot à l'établi",
  "robot-poignet-technicien-casque.jpg": "Technicien concentré, les mains sur le poignet d'un robot",
  "robot-portable-diagnostic-cellule.jpg": "Diagnostic sur une cellule robotisée, portable en main",
  "robot-pupitre-apprentissage-soudure.jpg": "Technicien senior au pupitre d'apprentissage d'un robot de soudure",
  "robot-soudure-points-caisse.jpg": "Robot de soudure par points sur une caisse en blanc",
  "robot-technicienne-inspection-bras.jpg": "Technicienne inspectant des bras robotisés, dossier en main",
  "soudure-brossage-meuleuse-etau.jpg": "Brossage d'un cordon de soudure à la meuleuse, pièce en étau",
  "soudure-corps-vanne-forge.jpg": "Soudeur accroupi sur un corps de vanne forgé",
  "soudure-fond-bombe-gabarit.jpg": "Soudage d'un fond bombé sur gabarit, vue d'atelier",
  "soudure-interieur-virole.jpg": "Soudeur à l'intérieur d'une virole de grand diamètre",
  "soudure-soudeuse-masque-releve.jpg": "Soudeuse expérimentée concentrée, masque relevé",
  "soudure-tig-virole-inox.jpg": "Gros plan d'un soudage TIG sur virole inox",
  "soudure-virole-inox-hall.jpg": "Soudeur sur une grande virole inox en atelier de chaudronnerie",
  "tuyau-pointage-bride-tube.jpg": "Pointage d'une bride sur un tube, mains gantées",
  "tuyau-soudure-reseau-usine.jpg": "Soudeur en intervention sur un réseau de tuyauterie en usine",
  "tuyau-vanne-volant-conserverie.jpg": "Vanne à volant et tuyauteries inox dans une conserverie",
  "tuyau-vanne-volant-rack.jpg": "Technicien manœuvrant une vanne à volant sur un rack de tuyauteries",
};

/**
 * La description de la photo designee par `chemin`, ou `null` si le chemin
 * ne designe pas une photo du registre (un logo, une image de la maquette).
 *
 * Accepte aussi bien "/assets/photos/x.jpg" que l'adresse optimisee par Next,
 * ou le chemin porte une seule fois, encode, dans le parametre `url`.
 */
export function descriptionPhoto(chemin: string | null | undefined): string | null {
  if (!chemin) return null;
  let brut = chemin;
  try {
    brut = decodeURIComponent(chemin);
  } catch {
    // Chemin deja decode, ou mal encode : on travaille sur l'original.
  }
  const fichier = brut.split("/assets/photos/")[1]?.split(/[?&#]/)[0];
  if (!fichier) return null;
  return DESCRIPTIONS[fichier] ?? null;
}

/**
 * Le texte alternatif a poser sur une image de contenu : la description du
 * registre quand elle existe, sinon la chaine vide, qui annonce correctement
 * une image decorative plutot que de laisser un lecteur d'ecran enoncer le
 * nom du fichier.
 */
export function altPhoto(chemin: string | null | undefined): string {
  return descriptionPhoto(chemin) ?? "";
}

/** Le nombre de photos decrites, pour les portes. */
export const NOMBRE_DECRITES = 385;
