-- Arborescence du site, en BROUILLON. Le contenu et la publication
-- viennent de l'import du corpus (supabase/import/0002_contenu_*.sql).
-- Le path est calculé par trigger : la colonne reçoit '' et le trigger l'écrase.
begin;

-- niveau 1 : 23 pages
insert into pages (niveau, slug, path, titre_h1, statut)
select 1, v.slug, '', v.h1, 'draft' from (values
  ('a-propos','À propos'),
  ('bureau-etudes','Bureau d''étude mécanique : un plan qui tient au montage'),
  ('carriere','Le terrain, avec les moyens de bien le faire.'),
  ('confidentialite','Politique de confidentialité'),
  ('contact','Dites-nous ce qu''il faut tenir.'),
  ('entreprise-maintenance-industrielle','Entreprise de maintenance industrielle'),
  ('equipe','Vos interlocuteurs, avec un nom et un numéro.'),
  ('expertises','Maintenance des équipements industriels'),
  ('guides','Guides'),
  ('implantations','Un siège à Lyon, dix hubs de techniciens, des interventions partout en France.'),
  ('lp','Votre service de maintenance industrielle : des techniciens qualifiés en renfort sur votre site.'),
  ('mentions-legales','Mentions légales'),
  ('modeles','Modèles'),
  ('nous-connaitre','Un seul métier : technicien de maintenance.'),
  ('offres','Entreprise maintenance industrielle'),
  ('partenaires','Nos offres en partenariat, 100 % Made in France.'),
  ('preuves','Ce que nous avons livré, chez qui, et en combien de temps.'),
  ('realisations','Ce que nous avons tenu, site par site.'),
  ('ressources','Guide maintenance industrielle'),
  ('rse','En maintenance, la RSE se mesure en machines qu’on ne jette pas.'),
  ('secteurs','La maintenance usine, secteur par secteur'),
  ('travaux-industriels','Travaux industriels'),
  ('valeurs','Cinq règles, et la preuve qui va avec.')
) as v(slug, h1)
on conflict (parent_id, slug) do nothing;

-- niveau 2 : 116 pages
insert into pages (parent_id, niveau, slug, path, titre_h1, statut)
select p.id, 2, v.slug, '', v.h1, 'draft' from (values
  ('/a-propos/','equipe','Vos interlocuteurs'),
  ('/bureau-etudes/','bureau-etude-electrique','Bureau d''étude électrique : du schéma à l''armoire qui tourne'),
  ('/bureau-etudes/','bureau-etude-electronique','Bureau d''étude électronique : une carte pensée pour être réparée'),
  ('/bureau-etudes/','mise-en-conformite-machine','Mise en conformité machine : fixez le calendrier avant l''inspection'),
  ('/carriere/','agent-de-maintenance','Agent de maintenance industrielle'),
  ('/carriere/','alternance','Alternance maintenance industrielle'),
  ('/carriere/','automaticien','Automaticien'),
  ('/carriere/','electromecanicien','Électromécanicien'),
  ('/carriere/','responsable-maintenance','Responsable maintenance'),
  ('/carriere/','roboticien','Roboticien'),
  ('/carriere/','technicien-de-maintenance','Technicien de maintenance'),
  ('/carriere/','technicien-itinerant','Technicien de maintenance itinérant'),
  ('/expertises/','automatisme','Automatisme industriel'),
  ('/expertises/','electrique','Maintenance électrique industrielle'),
  ('/expertises/','electromecanique','Électromécanique industrielle'),
  ('/expertises/','hydraulique','Maintenance hydraulique'),
  ('/expertises/','mecanique','Maintenance mécanique'),
  ('/expertises/','pneumatique','Maintenance pneumatique'),
  ('/expertises/','robotique','Maintenance robotique'),
  ('/expertises/','soudure','Soudure industrielle'),
  ('/expertises/','specialisations-constructeur','Automaticien industriel multimarques'),
  ('/expertises/','tuyauterie','Maintenance tuyauterie industrielle'),
  ('/expertises/','types-de-maintenance','Types de maintenance'),
  ('/guides/','choisir-une-entreprise-de-maintenance','Comment choisir une entreprise de maintenance industrielle'),
  ('/guides/','reussir-un-transfert-industriel','Réussir un transfert industriel : la méthode de bout en bout'),
  ('/implantations/','lille','La maintenance industrielle à Lille et dans les Hauts-de-France'),
  ('/implantations/','lyon','La maintenance industrielle à Lyon, depuis notre siège'),
  ('/implantations/','maintenance-industrielle-avignon','Maintenance industrielle à Avignon et dans le Vaucluse'),
  ('/implantations/','maintenance-industrielle-besancon','Maintenance industrielle à Besançon et dans le Doubs'),
  ('/implantations/','maintenance-industrielle-caen','Maintenance industrielle à Caen et dans le Calvados'),
  ('/implantations/','maintenance-industrielle-clermont-ferrand','Maintenance industrielle à Clermont-Ferrand et dans le Puy-de-Dôme'),
  ('/implantations/','maintenance-industrielle-dijon','Maintenance industrielle à Dijon et en Côte-d''Or'),
  ('/implantations/','maintenance-industrielle-dunkerque','Maintenance industrielle à Dunkerque et sur le littoral'),
  ('/implantations/','maintenance-industrielle-le-havre','Maintenance industrielle au Havre et dans l''estuaire de la Seine'),
  ('/implantations/','maintenance-industrielle-le-mans','Maintenance industrielle au Mans et dans la Sarthe'),
  ('/implantations/','maintenance-industrielle-limoges','Maintenance industrielle à Limoges et en Haute-Vienne'),
  ('/implantations/','maintenance-industrielle-marseille','Maintenance industrielle à Marseille et dans les Bouches-du-Rhône'),
  ('/implantations/','maintenance-industrielle-metz','Maintenance industrielle à Metz et en Moselle'),
  ('/implantations/','maintenance-industrielle-montpellier','Maintenance industrielle à Montpellier et dans l''Hérault'),
  ('/implantations/','maintenance-industrielle-nice','Maintenance industrielle à Nice et dans les Alpes-Maritimes'),
  ('/implantations/','maintenance-industrielle-orleans','Maintenance industrielle à Orléans et dans le Loiret'),
  ('/implantations/','maintenance-industrielle-pau','Maintenance industrielle à Pau et dans le Béarn'),
  ('/implantations/','maintenance-industrielle-poitiers','Maintenance industrielle à Poitiers et dans la Vienne'),
  ('/implantations/','maintenance-industrielle-reims','Maintenance industrielle à Reims et dans la Marne'),
  ('/implantations/','maintenance-industrielle-tours','Maintenance industrielle à Tours et en Touraine'),
  ('/implantations/','maintenance-industrielle-troyes','Maintenance industrielle à Troyes et dans l''Aube'),
  ('/implantations/','maintenance-industrielle-valenciennes','Maintenance industrielle à Valenciennes et dans le Nord'),
  ('/implantations/','nantes','La maintenance industrielle à Nantes et dans l''estuaire'),
  ('/implantations/','paris','Maintenir vos machines dans le tissu le plus dense de France'),
  ('/implantations/','strasbourg','La maintenance industrielle à Strasbourg et dans le Bas-Rhin'),
  ('/implantations/','toulouse','La maintenance industrielle à Toulouse et dans le Sud-Ouest'),
  ('/modeles/','article','Pourquoi faire appel à une entreprise de maintenance externalisée ?'),
  ('/modeles/','departement','Maintenance industrielle dans le Rhône'),
  ('/modeles/','domaine','Maintenance en automatisme industriel'),
  ('/modeles/','metier','Technicien de maintenance industrielle'),
  ('/modeles/','realisation','Remise en état complète d''un site industriel'),
  ('/modeles/','ressource','Pourquoi faire appel à une entreprise de maintenance externalisée ?'),
  ('/modeles/','secteur','Maintenance en agroalimentaire'),
  ('/modeles/','service-ville','Maintenance industrielle à Lyon, sans rupture de production'),
  ('/offres/','arret-technique','Arrêt technique maintenance'),
  ('/offres/','audit-conseil-maintenance','Conseil en maintenance industrielle : sachez où part le budget'),
  ('/offres/','bureau-etudes','Bureau d''études mécanique'),
  ('/offres/','chantier','Transfert industriel'),
  ('/offres/','construction','Montage industriel'),
  ('/offres/','depannage-industriel','Dépannage industriel'),
  ('/offres/','maintenance-externalisee','Un seul partenaire pour entretenir, réparer et remettre en production'),
  ('/offres/','residence','Sous-traitance maintenance'),
  ('/offres/','retrofit','Retrofit machine industrielle'),
  ('/offres/','zero-arret','Contrat de maintenance'),
  ('/preuves/','aktid-centre-logistique','Étude de cas AKTID : montage d''un centre logistique'),
  ('/preuves/','alstef-group','Étude de cas ALSTEF Group : contrôle de chantier'),
  ('/preuves/','amazon-centre-logistique','Étude de cas AMAZON : maintien d''un centre logistique'),
  ('/preuves/','amazon-nouveau-site','Étude de cas AMAZON : démarrage d''un nouveau site'),
  ('/preuves/','autoliv','Étude de cas AUTOLIV : maintien d''un site'),
  ('/preuves/','danone-lignes-de-production','Étude de cas DANONE : lignes de production'),
  ('/preuves/','eaton-mise-en-production','Étude de cas EATON : mise en production'),
  ('/preuves/','eiffage','EIFFAGE : trois techniciens sur un chantier photovoltaïque'),
  ('/preuves/','eriks','ERIKS : un responsable maintenance pendant la transition'),
  ('/preuves/','fdj','FDJ : un technicien de maintenance en continu sur les lignes'),
  ('/preuves/','gls-maintenance-curative','Étude de cas GLS : maintenance curative'),
  ('/preuves/','groupe-atlantic','GROUPE ATLANTIC : un renfort permanent sur les sites de production'),
  ('/preuves/','joint-lyonnais','JOINT LYONNAIS : des machines réparées, pas remplacées'),
  ('/preuves/','jtekt','Étude de cas JTEKT : maintenance des installations'),
  ('/preuves/','mccain-belgique','Étude de cas McCAIN : Belgique'),
  ('/preuves/','mersen','MERSEN : sécuriser le démarrage d''une ligne neuve'),
  ('/preuves/','ogf-arret-estival','OGF : passer l''été sans trou dans la maintenance'),
  ('/preuves/','orthus-ecocem','ORTHUS x ECOCEM : construire un site de R&D industriel'),
  ('/preuves/','orthus-washtec','ORTHUS x WASHTEC : monter des portiques partout en France'),
  ('/preuves/','soprema','SOPREMA : montage, transfert de machines et renfort de chantier'),
  ('/preuves/','stellantis-fonderie-sept-fons','STELLANTIS, fonderie de Sept-Fons : un parc repris en 8 semaines'),
  ('/preuves/','stellantis-grand-est','Étude de cas STELLANTIS : sites du Grand Est'),
  ('/preuves/','suez-remise-en-etat','SUEZ IWT : un électromécanicien habilité pour une remise en état'),
  ('/preuves/','timescope','TIMESCOPE : tenir un parc de casques déployé en France'),
  ('/preuves/','valeo-usines','Étude de cas VALEO : plusieurs usines'),
  ('/preuves/','veepee-sites-lyon','Étude de cas VEEPEE : sites de Lyon'),
  ('/preuves/','voit-grand-est','Étude de cas VOIT : site du Grand Est'),
  ('/preuves/','vpk','VPK : un technicien polyvalent sur un parc en forte cadence'),
  ('/ressources/','articles','Ressources : Articles'),
  ('/ressources/','fiches-pratiques','Ressources : Fiches pratiques'),
  ('/ressources/','fiches-techniques','Ressources : Fiches techniques'),
  ('/ressources/','livres-blancs','Ressources : Livres blancs'),
  ('/ressources/','process','Ressources : Process'),
  ('/secteurs/','aeronautique','Maintenance dans l''industrie aéronautique'),
  ('/secteurs/','agroalimentaire','Maintenance agroalimentaire'),
  ('/secteurs/','automobile','Maintenance dans l''industrie automobile'),
  ('/secteurs/','chimie','Maintenance dans l''industrie chimique'),
  ('/secteurs/','industrie-lourde','Maintenance dans l''industrie lourde'),
  ('/secteurs/','industrie-metallique','Maintenance dans l''industrie métallique'),
  ('/secteurs/','logistique','Maintenance des équipements logistiques'),
  ('/secteurs/','menuiserie-industrielle','Maintenance en menuiserie industrielle'),
  ('/secteurs/','nucleaire','Maintenance nucléaire'),
  ('/secteurs/','pharmaceutique','Maintenance pharmaceutique'),
  ('/travaux-industriels/','demantelement-industriel','Démantèlement industriel'),
  ('/travaux-industriels/','levage-manutention','Levage industriel et manutention lourde'),
  ('/travaux-industriels/','montage-industriel','Montage industriel : machines, lignes et équipements de production'),
  ('/travaux-industriels/','transfert-industriel','Transfert industriel et déménagement de machines industrielles')
) as v(pp, slug, h1) join pages p on p.path = v.pp
on conflict (parent_id, slug) do nothing;

-- niveau 3 : 86 pages
insert into pages (parent_id, niveau, slug, path, titre_h1, statut)
select p.id, 3, v.slug, '', v.h1, 'draft' from (values
  ('/carriere/automaticien/','salaire','Salaire automaticien'),
  ('/carriere/electromecanicien/','competences','Compétences électromécanicien'),
  ('/carriere/electromecanicien/','salaire','Salaire électromécanicien'),
  ('/carriere/technicien-de-maintenance/','formation','Formation technicien de maintenance'),
  ('/carriere/technicien-de-maintenance/','salaire','Salaire technicien de maintenance'),
  ('/expertises/automatisme/','programmation-automate','Programmation automate'),
  ('/expertises/automatisme/','schneider','Automate schneider'),
  ('/expertises/automatisme/','siemens','Automaticien Siemens'),
  ('/expertises/hydraulique/','verin-hydraulique','Réparation vérin hydraulique'),
  ('/expertises/mecanique/','lubrification','Lubrification industrielle'),
  ('/expertises/mecanique/','machine-outil','Maintenance machine outil'),
  ('/expertises/robotique/','abb','Maintenance de robots ABB'),
  ('/expertises/robotique/','fanuc','Fanuc robotique'),
  ('/expertises/robotique/','integrateur-robotique','Intégrateur robotique'),
  ('/expertises/tuyauterie/','nettoyage','Nettoyage tuyauterie industrielle'),
  ('/expertises/types-de-maintenance/','maintenance-ameliorative','Maintenance améliorative'),
  ('/expertises/types-de-maintenance/','maintenance-conditionnelle','Maintenance conditionnelle'),
  ('/expertises/types-de-maintenance/','maintenance-corrective','Maintenance corrective'),
  ('/expertises/types-de-maintenance/','maintenance-curative','Maintenance curative'),
  ('/expertises/types-de-maintenance/','maintenance-palliative','Maintenance palliative'),
  ('/expertises/types-de-maintenance/','maintenance-predictive','Maintenance prédictive'),
  ('/expertises/types-de-maintenance/','maintenance-preventive','Maintenance préventive'),
  ('/expertises/types-de-maintenance/','maintenance-previsionnelle','Maintenance prévisionnelle'),
  ('/expertises/types-de-maintenance/','preventive-systematique','Maintenance préventive systématique'),
  ('/implantations/lyon/','grenoble','La maintenance industrielle à Grenoble et dans l''Isère'),
  ('/implantations/lyon/','haute-savoie','La maintenance industrielle en Haute-Savoie, de l''Arve au Genevois'),
  ('/implantations/lyon/','rhone','La maintenance industrielle dans le Rhône, du Beaujolais à Feyzin'),
  ('/implantations/lyon/','saint-etienne','Maintenance industrielle à Saint-Étienne et dans la Loire'),
  ('/implantations/lyon/','valence','La maintenance industrielle à Valence et dans la Drôme'),
  ('/implantations/nantes/','brest','Maintenance industrielle à Brest et dans le Finistère'),
  ('/implantations/nantes/','loire-atlantique','Maintenance industrielle en Loire-Atlantique'),
  ('/implantations/nantes/','rennes','Maintenance industrielle à Rennes et en Ille-et-Vilaine'),
  ('/implantations/paris/','essonne','Maintenance industrielle en Essonne'),
  ('/implantations/paris/','rouen','Maintenance industrielle à Rouen et dans la vallée de Seine'),
  ('/implantations/strasbourg/','alsace','Maintenance industrielle en Alsace, du Bas-Rhin au Haut-Rhin'),
  ('/implantations/strasbourg/','mulhouse','Maintenance industrielle à Mulhouse et dans le Haut-Rhin'),
  ('/implantations/toulouse/','bordeaux','Maintenance industrielle à Bordeaux et dans la métropole'),
  ('/implantations/toulouse/','charente','Maintenance industrielle en Charente'),
  ('/implantations/toulouse/','gironde','Maintenance industrielle en Gironde'),
  ('/implantations/toulouse/','haute-garonne','Maintenance industrielle en Haute-Garonne'),
  ('/offres/chantier/','demenagement-machines','Déménagement de machines industrielles'),
  ('/offres/chantier/','transfert-de-production','Transfert de production'),
  ('/offres/depannage-industriel/','astreinte','Astreinte de maintenance, 24 heures sur 24'),
  ('/offres/depannage-industriel/','panne-machine','Panne machine industrielle : agir dans la première heure'),
  ('/offres/residence/','cahier-des-charges','Cahier des charges de maintenance : la trame à reprendre'),
  ('/offres/residence/','prestataire-ou-salarie','Prestataire ou salarié : le comparatif honnête'),
  ('/offres/residence/','recruter-un-technicien','Recruter un technicien de maintenance'),
  ('/offres/retrofit/','mise-en-conformite-machine','Mise en conformité des machines : fixez le calendrier avant l''inspection'),
  ('/offres/retrofit/','remise-en-etat','Remise en état machine industrielle'),
  ('/ressources/articles/','cout-arret-de-production','Coût d''un arrêt de production'),
  ('/ressources/articles/','digitalisation-maintenance','Digitalisation maintenance'),
  ('/ressources/articles/','gestion-des-dechets','Gestion des déchets industriels'),
  ('/ressources/articles/','gmao','Gestion de maintenance assistée par ordinateur'),
  ('/ressources/articles/','ia-maintenance','IA maintenance : ce qui change vraiment'),
  ('/ressources/articles/','maintenance-4-0','Maintenance 4.0'),
  ('/ressources/articles/','optimiser-la-maintenance','Optimisation de la maintenance'),
  ('/ressources/articles/','organiser-service-maintenance','Comment organiser un service de maintenance'),
  ('/ressources/articles/','plan-de-maintenance','Plan de maintenance'),
  ('/ressources/articles/','planification-maintenance','Planning de maintenance'),
  ('/ressources/articles/','predictive-ou-corrective','Maintenance prédictive ou corrective'),
  ('/ressources/articles/','preventive-ou-corrective','Maintenance préventive et corrective'),
  ('/ressources/articles/','robot-spot','Robot spot'),
  ('/ressources/articles/','suivi-de-la-maintenance','Suivi de la maintenance'),
  ('/ressources/articles/','tpm','TPM, la maintenance productive totale'),
  ('/ressources/fiches-pratiques/','5s','5S industrie'),
  ('/ressources/fiches-pratiques/','consignation-electrique','Consignation électrique'),
  ('/ressources/fiches-pratiques/','permis-de-feu','Permis de feu'),
  ('/ressources/fiches-pratiques/','plan-de-prevention','Plan de prévention'),
  ('/ressources/fiches-pratiques/','securite-maintenance','La sécurité en maintenance industrielle'),
  ('/ressources/fiches-techniques/','amdec','Amdec'),
  ('/ressources/fiches-techniques/','analyse-vibratoire','Analyse vibratoire'),
  ('/ressources/fiches-techniques/','automates-siemens','Automate Siemens'),
  ('/ressources/fiches-techniques/','cahier-des-charges-gmao','Cahier des charges gmao'),
  ('/ressources/fiches-techniques/','indicateurs-maintenance','Indicateur maintenance'),
  ('/ressources/fiches-techniques/','mtbf-mttr','Mtbf'),
  ('/ressources/fiches-techniques/','niveaux-de-maintenance','Niveaux de maintenance'),
  ('/ressources/fiches-techniques/','outils-de-diagnostic','Outils de diagnostic maintenance'),
  ('/ressources/fiches-techniques/','trs','TRS : le taux de rendement synthétique'),
  ('/ressources/livres-blancs/','externaliser-sa-maintenance','Livre blanc : externaliser sa maintenance sans perdre la main'),
  ('/ressources/livres-blancs/','retrofit-ou-remplacement','Retrofit ou remplacement'),
  ('/ressources/process/','gestion-maintenance-preventive','Gestion de la maintenance préventive'),
  ('/ressources/process/','preparer-un-arret-technique','Préparation arrêt technique'),
  ('/ressources/process/','protocole-de-securite','Protocole de sécurité'),
  ('/ressources/process/','selection-des-techniciens','Sélection technicien de maintenance'),
  ('/secteurs/logistique/','maintenance-convoyeur','Maintenance convoyeur'),
  ('/secteurs/logistique/','peak-season','Peak season : préparer la logistique au pic')
) as v(pp, slug, h1) join pages p on p.path = v.pp
on conflict (parent_id, slug) do nothing;

-- SEO : 222 lignes, meta reprises telles quelles du site en ligne
insert into seo (page_id, meta_title, meta_description)
select p.id, v.t, v.d from (values
  ('/a-propos/equipe/','L''équipe Migen, de la direction au terrain | Migen','Qui pilote vos interventions chez Migen : direction, chargés d''affaires, référents techniques et plus de 100 collaborateurs, de Lyon à Toulouse.'),
  ('/bureau-etudes/','Bureau d''étude mécanique et ingénierie | Migen','Bureau d''étude mécanique, électronique et pneumatique : conception, calculs, dossier de fabrication, montage. Rappel dans l''heure au 04 78 33 72 05.'),
  ('/bureau-etudes/bureau-etude-electrique/','Bureau d''étude électrique industriel | Migen','Bureau d''étude électrique : relevé de l''existant, schémas, armoire, dossier technique, raccordement et mise en service par nos électriciens. 04 78 33 72 05.'),
  ('/bureau-etudes/bureau-etude-electronique/','Bureau d''étude électronique industrielle | Migen','Bureau d''étude électronique : conception électronique, carte, obsolescence, intégration machine, par des équipes qui dépannent toute l''année. 04 78 33 72 05.'),
  ('/bureau-etudes/mise-en-conformite-machine/','Mise en conformité machine : audit et travaux | Migen','Mise en conformité machine : ce que la réglementation exige, comment se déroule l''audit, et qui réalise les travaux. Techniciens évalués, rappel dans l''heure.'),
  ('/carriere/','Carrière, migen','Rejoignez migen : habilitations prises en charge, formation continue, missions chez des industriels de premier rang. Postes ouverts et candidature en quatre écrans.'),
  ('/carriere/agent-de-maintenance/','Agent de maintenance industrielle | Migen','Agent de maintenance industrielle : missions, habilitations, formation et salaire du métier. Migen recrute des agents de maintenance partout en France.'),
  ('/carriere/alternance/','Alternance maintenance industrielle | Migen','Alternance maintenance industrielle : rémunération, habilitations financées, missions proches de chez vous. Migen forme ses alternants techniciens. Postulez.'),
  ('/carriere/automaticien/','Automaticien | Migen','Automaticien : missions, automates, habilitations et salaire du métier. Migen recrute des automaticiens Siemens et Schneider partout en France.'),
  ('/carriere/automaticien/salaire/','Salaire automaticien : fourchettes et évolution | Migen','Salaire automaticien : fourchettes réelles par expérience, secteur et région, et ce qui fait monter la rémunération. Par Migen, employeur d''automaticiens.'),
  ('/carriere/electromecanicien/','Électromécanicien | Migen','Électromécanicien : missions, habilitations, formation et salaire du métier. Migen recrute des électromécaniciens de maintenance industrielle partout en France.'),
  ('/carriere/electromecanicien/competences/','Compétences électromécanicien | Migen','Compétences électromécanicien : savoir-faire techniques, diagnostic, sécurité et qualités attendues. Migen recrute des électromécaniciens en France.'),
  ('/carriere/electromecanicien/salaire/','Salaire électromécanicien | Migen','Salaire électromécanicien : ce qui fait varier la rémunération, du débutant au confirmé, par secteur et région. Migen recrute partout en France.'),
  ('/carriere/responsable-maintenance/','Responsable maintenance | Migen','Responsable maintenance : missions, compétences, formation et salaire du métier. Migen recrute et forme les responsables maintenance de l''industrie en France.'),
  ('/carriere/roboticien/','Roboticien | Migen','Roboticien : missions, robots, formation et salaire du métier. Migen recrute des roboticiens ABB et Fanuc pour la maintenance robotique industrielle en France.'),
  ('/carriere/technicien-de-maintenance/','Technicien de maintenance | Migen','Technicien de maintenance : missions, compétences, formation, salaire et emploi du métier. Migen recrute des techniciens de maintenance en France.'),
  ('/carriere/technicien-de-maintenance/formation/','Formation technicien de maintenance | Migen','Formation technicien de maintenance : diplômes, alternance, titre professionnel, reconversion adulte et débouchés. Migen recrute partout en France.'),
  ('/carriere/technicien-de-maintenance/salaire/','Salaire technicien de maintenance : fourchettes | Migen','Salaire technicien de maintenance : fourchettes réelles par expérience, secteur et région, et ce qui fait monter la rémunération. Par Migen, employeur.'),
  ('/carriere/technicien-itinerant/','Technicien de maintenance itinérant | Migen','Technicien de maintenance itinérant : missions, déplacements, salaire et CDI. Migen recrute des techniciens itinérants pour intervenir chez ses clients en France.'),
  ('/confidentialite/','Politique de confidentialité, migen','Traitement des données personnelles, cookies et exercice de vos droits sur le site migen.'),
  ('/contact/','Contact & devis, migen','Décrivez votre besoin : un chargé d''affaires sélectionne les profils adaptés et vous rappelle dans l''heure aux horaires ouvrés. Astreinte 7 j/7.'),
  ('/entreprise-maintenance-industrielle/','Prestataire maintenance industrielle en France | Migen','Entreprise maintenance industrielle partout en France : techniciens évalués, 10 % des candidats retenus, rappel dans l''heure, astreinte 24/24 et 7/7.'),
  ('/equipe/','Équipe & direction, migen','Les femmes et les hommes de migen : direction, chargés d''affaires et équipes qui pilotent vos projets industriels.'),
  ('/expertises/','Maintenance des équipements industriels | Migen','Maintenance des équipements industriels : dix domaines techniques, des techniciens de maintenance évalués, seuls 10 % des candidats retenus.'),
  ('/expertises/automatisme/','Automaticien SIEMENS et Schneider sur site | Migen','Automatisme industriel : diagnostic d''automate, reprise de programme, sauvegardes, migration d''obsolescence. Automaticiens évalués, rappel dans l''heure.'),
  ('/expertises/automatisme/programmation-automate/','Automaticien pour reprendre votre code | Migen','Programmation automate : reprise de code orphelin, dépannage par le programme, migration Siemens et Schneider. Automaticiens évalués, rappel dans l''heure.'),
  ('/expertises/automatisme/schneider/','Dépannage automate Modicon Schneider | Migen','Automate Schneider : diagnostic, dépannage et reprise de programme sur toute la gamme Modicon. Automaticiens évalués, rappel dans l''heure.'),
  ('/expertises/automatisme/siemens/','Automaticien Siemens SIMATIC et TIA Portal | Migen','Automaticien Siemens : diagnostic, dépannage et reprise de programme sur parc SIMATIC, TIA Portal et STEP 7. Techniciens évalués, rappel dans l''heure.'),
  ('/expertises/electrique/','Électricien de maintenance industrielle | Migen','Maintenance électrique industrielle : armoires, moteurs, variateurs, thermographie. Techniciens habilités partout en France, rappel dans l''heure.'),
  ('/expertises/electromecanique/','Électromécanicien de maintenance sur site | Migen','Électromécanique industrielle : moteurs, variateurs, transmissions, capteurs diagnostiqués par un seul intervenant. Rappel dans l''heure, partout en France.'),
  ('/expertises/hydraulique/','Dépannage de circuits hydrauliques | Migen','Maintenance hydraulique industrielle : pression, fuites, vérins, centrales, analyse de fluide. Techniciens évalués partout en France, rappel dans l''heure.'),
  ('/expertises/hydraulique/verin-hydraulique/','Réparer un vérin hydraulique plutôt que le remplacer','Réparation vérin hydraulique : diagnostic sur site, démontage, joints neufs, essais en pression et remise en service. Toutes marques. Rappel dans l''heure.'),
  ('/expertises/mecanique/','Mécanicien de maintenance sur site | Migen','Maintenance mécanique industrielle : roulements, transmissions, convoyeurs, presses. Mécaniciens évalués, partout en France. Rappel dans l''heure.'),
  ('/expertises/mecanique/lubrification/','Plan de graissage et analyse d''huile | Migen','Lubrification industrielle : plan de graissage écrit, analyse d''huile et rondes tenues par des techniciens évalués. Rappel dans l''heure, partout en France.'),
  ('/expertises/mecanique/machine-outil/','Maintenance de tours et centres d''usinage | Migen','Maintenance machine outil : diagnostic, géométrie, axes et commande numérique sur tour, fraiseuse et centre d''usinage. Rappel dans l''heure.'),
  ('/expertises/pneumatique/','Air comprimé industriel : chasse aux fuites | Migen','Maintenance pneumatique industrielle : fuites d''air comprimé, vérins, distributeurs, sécheurs et filtres. Techniciens évalués, rappel dans l''heure.'),
  ('/expertises/robotique/','Roboticien ABB et Fanuc pour votre cellule | Migen','Maintenance robotique : préventif, dépannage et remise en service de vos robots industriels. Roboticiens ABB et Fanuc évalués, rappel dans l''heure.'),
  ('/expertises/robotique/abb/','Roboticien ABB indépendant | Migen','ABB robotique : dépannage, préventif et remise en précision de vos robots ABB par des roboticiens évalués. Rappel dans l''heure, partout en France.'),
  ('/expertises/robotique/fanuc/','Maintenance de robots Fanuc sur site | Migen','Fanuc robotique : dépannage, préventif et remise en service de vos robots et machines Fanuc. Techniciens évalués, sauvegardes datées, rappel dans l''heure.'),
  ('/expertises/robotique/integrateur-robotique/','Reprendre une cellule après l''intégrateur | Migen','Intégrateur robotique : nous reprenons la cellule après l''installation, mise en service, réglage, dépannage. Roboticiens évalués, rappel dans l''heure.'),
  ('/expertises/soudure/','Soudeur de maintenance sur votre site | Migen','Soudure industrielle de réparation : châssis fissurés, rechargement, tôlerie de maintenance. Procédés MIG, MAG, TIG, arc. Rappel dans l''heure.'),
  ('/expertises/specialisations-constructeur/','Automaticien Siemens, Schneider, Allen Bradley | Migen','Automaticien industriel multimarques : Siemens, Schneider, Rockwell, machines spéciales. Techniciens évalués, rappel dans l''heure, partout en France.'),
  ('/expertises/tuyauterie/','Tuyauteur industriel : fuites et tronçons | Migen','Maintenance tuyauterie industrielle : fuites, mesure d''épaisseur, remplacement de tronçons, essais en pression. Techniciens évalués, rappel dans l''heure.'),
  ('/expertises/tuyauterie/nettoyage/','Nettoyage de tuyauterie industrielle | Migen','Nettoyage tuyauterie industrielle : diagnostic du dépôt, décapage chimique ou mécanique, rinçage et réception écrite. Rappel dans l''heure.'),
  ('/expertises/types-de-maintenance/','Quel type de maintenance choisir | Migen','Types de maintenance : corrective, curative, préventive, conditionnelle, prévisionnelle, prédictive. Ce que chacune déclenche, et comment les doser.'),
  ('/expertises/types-de-maintenance/maintenance-ameliorative/','Supprimer la panne qui revient | Migen','Maintenance améliorative : supprimer la cause des pannes qui reviennent au lieu de réparer deux fois. Techniciens évalués, rappel dans l''heure.'),
  ('/expertises/types-de-maintenance/maintenance-conditionnelle/','Intervenir sur l''état réel, pas sur le calendrier | Migen','Maintenance conditionnelle : définition NF EN 13306, technologies de surveillance, seuils et mise en place. Puis qui relève et qui interprète chez vous.'),
  ('/expertises/types-de-maintenance/maintenance-corrective/','Réparer après la panne, et arrêter de payer | Migen','Maintenance corrective : définition, immédiate ou différée, avantages, limites et coût réel. Puis comment ramener le correctif à une part minoritaire.'),
  ('/expertises/types-de-maintenance/maintenance-curative/','Réparer pour de bon, cause racine traitée | Migen','Maintenance curative : définition, différence avec la corrective, déroulé d''une intervention, coût complet et indicateurs. Puis qui répare vraiment.'),
  ('/expertises/types-de-maintenance/maintenance-palliative/','Maintenance palliative : dépannage provisoire | Migen','Maintenance palliative : remise en marche provisoire de votre équipement, réparation définitive tracée. Techniciens évalués, rappel dans l''heure.'),
  ('/expertises/types-de-maintenance/maintenance-predictive/','Voir la panne venir, et la planifier | Migen','Maintenance prédictive : définition, capteurs, données, modèles et retour sur investissement. Puis qui exécute les travaux que le modèle annonce.'),
  ('/expertises/types-de-maintenance/maintenance-preventive/','Plan de maintenance préventive tenu | Migen','Maintenance préventive : définition, les 3 types, le plan en 5 étapes et les indicateurs. Puis qui exécute les campagnes quand vos équipes sont prises.'),
  ('/expertises/types-de-maintenance/maintenance-previsionnelle/','Suivre la tendance, programmer avant la casse | Migen','Maintenance prévisionnelle : définition, signaux de dégradation, chaîne de la donnée et mise en place en 6 étapes. Puis qui exécute ce que la pente annonce.'),
  ('/expertises/types-de-maintenance/preventive-systematique/','Programme de préventif systématique tenu | Migen','Maintenance préventive systématique : gammes écrites, périodicité juste, échéancier tenu par des techniciens évalués. Rappel dans l''heure.'),
  ('/guides/choisir-une-entreprise-de-maintenance/','Choisir son prestataire de maintenance | Migen','Entreprise maintenance industrielle : les critères qui comptent, les questions à poser en rendez-vous, les signaux d''alerte et comment comparer deux devis.'),
  ('/guides/reussir-un-transfert-industriel/','Transfert industriel : le guide complet | Migen','Transfert industriel : la méthode de bout en bout, de l''inventaire des machines au redémarrage. Ordre de démontage, repérage, remontage, essais, checklist.'),
  ('/implantations/','Maintenance industrielle partout en France | Migen','Maintenance industrielle France : quatre agences dont Lyon, notre siège, des hubs de techniciens, des interventions partout ailleurs. Rappel dans l''heure.'),
  ('/implantations/lille/','Maintenance industrielle Lille : Hauts-de-France | Migen','Maintenance industrielle Lille : agroalimentaire, textile technique, ferroviaire du Valenciennois, sidérurgie de Dunkerque. Rappel dans l''heure.'),
  ('/implantations/lyon/','Maintenance industrielle Lyon : siège et hub | Migen','Maintenance industrielle Lyon : siège Migen à Limonest, dépannage et préventif de la vallée de la chimie à l''est lyonnais. Rappel dans l''heure.'),
  ('/implantations/lyon/grenoble/','Maintenance industrielle Grenoble : Isère | Migen','Maintenance industrielle Grenoble : microélectronique de Crolles, chimie du Pont-de-Claix, papeteries du Grésivaudan. Rappel dans l''heure, astreinte 24/7.'),
  ('/implantations/lyon/haute-savoie/','Maintenance industrielle Haute Savoie : Arve | Migen','Maintenance industrielle Haute Savoie : décolletage de la vallée de l''Arve, mécatronique d''Annecy, agroalimentaire du Chablais. Rappel dans l''heure.'),
  ('/implantations/lyon/rhone/','Maintenance industrielle Rhône : le département | Migen','Maintenance industrielle Rhône : vallée de la chimie, est lyonnais, val de Saône et Beaujolais. Techniciens évalués, rappel dans l''heure, astreinte 24/7.'),
  ('/implantations/lyon/saint-etienne/','Maintenance industrielle Saint-Étienne, Loire | Migen','Maintenance industrielle Saint-Étienne : machines-outils, presses et lignes, de la vallée du Gier au Forez. Rappel dans l''heure, astreinte 24/24 en option.'),
  ('/implantations/lyon/valence/','Maintenance industrielle Valence : Drôme | Migen','Maintenance industrielle Valence : embouteillage et fruits de la plaine, Rovaltain, logistique de l''axe rhodanien. Rappel dans l''heure, astreinte 24/7.'),
  ('/implantations/maintenance-industrielle-avignon/','Maintenance industrielle Avignon et Vaucluse | Migen','Maintenance industrielle Avignon : dépannage, préventif et astreinte 24/24 et 7/7, de Courtine à Cavaillon et Sorgues. Rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-besancon/','Maintenance industrielle Besançon et le Doubs | Migen','Maintenance industrielle Besançon : dépannage, préventif et astreinte 24/24 et 7/7, de Temis à École-Valentin. Rappel dans l''heure, techniciens évalués.'),
  ('/implantations/maintenance-industrielle-caen/','Maintenance industrielle Caen : astreinte 24/24 | Migen','Maintenance industrielle Caen : dépannage, préventif et astreinte 24/24 et 7/7, de Mondeville à Colombelles. Rappel dans l''heure, techniciens évalués.'),
  ('/implantations/maintenance-industrielle-clermont-ferrand/','Maintenance industrielle Clermont-Ferrand | Migen','Maintenance industrielle Clermont-Ferrand : caoutchouc, agroalimentaire de Limagne, aéronautique d''Issoire. Techniciens évalués, rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-dijon/','Maintenance industrielle Dijon : dépannage 24/24 | Migen','Maintenance industrielle Dijon : agroalimentaire, pharmacie et usinage en Côte-d''Or, de Longvic au Val de Saône. Techniciens évalués, rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-dunkerque/','Maintenance industrielle Dunkerque et le port | Migen','Maintenance industrielle Dunkerque : dépannage, préventif et astreinte 24/24 et 7/7, de Grande-Synthe à Gravelines. Rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-le-havre/','Maintenance industrielle Le Havre : dépannage | Migen','Maintenance industrielle Le Havre : machines tournantes, procédés continus et manutention portuaire, par des techniciens évalués. Rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-le-mans/','Maintenance industrielle Le Mans : dépannage | Migen','Maintenance industrielle Le Mans : équipementiers automobiles, agroalimentaire sarthois et plasturgie. Techniciens évalués, rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-limoges/','Maintenance industrielle Limoges et Brive | Migen','Maintenance industrielle Limoges : dépannage, préventif et astreinte 24/24 et 7/7, de Saint-Junien à Brive-la-Gaillarde. Rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-marseille/','Maintenance industrielle Marseille : dépannage | Migen','Maintenance industrielle Marseille : techniciens habilités pour Fos, l''étang de Berre et les ateliers de Rousset. Rappel dans l''heure, astreinte 24/24.'),
  ('/implantations/maintenance-industrielle-metz/','Maintenance industrielle Metz : dépannage 24/24 | Migen','Maintenance industrielle Metz : métallurgie, automobile et logistique du sillon mosellan. Dispositif documenté sur un site messin, rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-montpellier/','Maintenance industrielle Montpellier, Hérault | Migen','Maintenance industrielle Montpellier : dépannage, préventif et astreinte 24/24 et 7/7, de Lattes à Béziers et Sète. Rappel dans l''heure, techniciens évalués.'),
  ('/implantations/maintenance-industrielle-nice/','Maintenance industrielle Nice et Alpes-Maritimes | Migen','Maintenance industrielle Nice : dépannage, préventif et astreinte 24/24 et 7/7, de Carros à Grasse et Cannes. Rappel dans l''heure, techniciens évalués.'),
  ('/implantations/maintenance-industrielle-orleans/','Maintenance industrielle Orléans : dépannage | Migen','Maintenance industrielle Orléans : plateformes logistiques de l''A10, cosmétique et pharmacie du Loiret. Techniciens évalués, rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-pau/','Maintenance industrielle Pau, Béarn et Lacq | Migen','Maintenance industrielle Pau : dépannage, préventif et astreinte 24/24 et 7/7, du bassin de Lacq à Serres-Castet. Rappel dans l''heure, techniciens évalués.'),
  ('/implantations/maintenance-industrielle-poitiers/','Maintenance industrielle Poitiers : dépannage | Migen','Maintenance industrielle Poitiers : mécanique de précision de Châtellerault, logistique du Futuroscope, carrières et levage. Rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-reims/','Maintenance industrielle Reims : dépannage 24/24 | Migen','Maintenance industrielle Reims : embouteillage, campagne betteravière et emballage dans la Marne. Techniciens évalués, rappel dans l''heure, astreinte.'),
  ('/implantations/maintenance-industrielle-tours/','Maintenance industrielle Tours : dépannage 24/24 | Migen','Maintenance industrielle Tours : façonnage, froid industriel et usinage en Touraine, de Saint-Pierre-des-Corps à Joué-lès-Tours. Rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-troyes/','Maintenance industrielle Troyes et Aube | Migen','Maintenance industrielle Troyes : dépannage, préventif et astreinte 24/24 et 7/7, de Sainte-Savine à Nogent-sur-Seine. Rappel dans l''heure.'),
  ('/implantations/maintenance-industrielle-valenciennes/','Maintenance industrielle Valenciennes, Nord | Migen','Maintenance industrielle Valenciennes : dépannage, préventif et astreinte 24/24 et 7/7, d''Onnaing à Denain et Douai. Rappel dans l''heure.'),
  ('/implantations/nantes/','Maintenance industrielle Nantes : hub technicien | Migen','Maintenance industrielle Nantes : aéronautique, naval et agroalimentaire du Grand Ouest. Techniciens évalués, rappel dans l''heure, astreinte 24/7.'),
  ('/implantations/nantes/brest/','Maintenance industrielle Brest et Finistère | Migen','Maintenance industrielle Brest : naval, agroalimentaire et levage portuaire, de Guipavas à Quimper. Techniciens évalués, rappel dans l''heure, astreinte.'),
  ('/implantations/nantes/loire-atlantique/','Maintenance industrielle Loire-Atlantique (44) | Migen','Maintenance industrielle Loire-Atlantique : naval de Saint-Nazaire, agroalimentaire, machinisme d''Ancenis. Hub de techniciens à Nantes, rappel dans l''heure.'),
  ('/implantations/nantes/rennes/','Maintenance industrielle Rennes et Ille-et-Vilaine | Migen','Maintenance industrielle Rennes : agroalimentaire, équipementiers auto de Chartres-de-Bretagne, électronique. Techniciens évalués, rappel dans l''heure.'),
  ('/implantations/paris/','Maintenance industrielle Paris : nos techniciens | Migen','Maintenance industrielle Paris : nos techniciens Migen basés à Paris, ateliers en fond de cour, entrepôts de couronne, axe Seine. Rappel dans l''heure.'),
  ('/implantations/paris/essonne/','Maintenance industrielle Essonne (91) | Migen','Maintenance industrielle Essonne : logistique de Massy, mécanique de Corbeil, pilotes de Saclay. Techniciens évalués, rappel dans l''heure, astreinte 24/24.'),
  ('/implantations/paris/rouen/','Maintenance industrielle Rouen, axe Seine | Migen','Maintenance industrielle Rouen : procédés continus, papier-carton, logistique portuaire de la vallée de Seine. Rappel dans l''heure, astreinte 24/24 en option.'),
  ('/implantations/strasbourg/','Maintenance industrielle Strasbourg : nos techniciens | Migen','Maintenance industrielle Strasbourg : port rhénan, brasseries, pharma d''Illkirch, automobile du Grand Est. Rappel dans l''heure, astreinte 24/7.'),
  ('/implantations/strasbourg/alsace/','Maintenance industrielle Alsace, Bas-Rhin et Haut-Rhin | Migen','Maintenance industrielle Alsace : brasserie, chimie, logistique rhénane, équipementiers auto. Hub de techniciens à Strasbourg, rappel dans l''heure.'),
  ('/implantations/strasbourg/mulhouse/','Maintenance industrielle Mulhouse, Haut-Rhin | Migen','Maintenance industrielle Mulhouse : automobile, mécanique et chimie du Sud-Alsace, de Thann à Saint-Louis. Techniciens évalués, rappel dans l''heure.'),
  ('/implantations/toulouse/','Maintenance industrielle Toulouse : nos techniciens | Migen','Maintenance industrielle Toulouse : aéronautique de Blagnac, logistique d''Eurocentre, agroalimentaire d''Occitanie. Rappel dans l''heure, astreinte 24/7.'),
  ('/implantations/toulouse/bordeaux/','Maintenance industrielle Bordeaux, Mérignac | Migen','Maintenance industrielle Bordeaux : chais et embouteillage, aéronautique de Mérignac, logistique de rocade. Techniciens évalués, rappel dans l''heure.'),
  ('/implantations/toulouse/charente/','Maintenance industrielle Charente, Angoulême | Migen','Maintenance industrielle charente : chais de Cognac, papier-carton d''Angoulême, carrières. Techniciens itinérants, rappel dans l''heure, astreinte cadrée.'),
  ('/implantations/toulouse/gironde/','Maintenance industrielle Gironde (33) | Migen','Maintenance industrielle Gironde : rive droite industrielle, chais du Libournais, scieries du massif landais. Rappel dans l''heure, astreinte en option.'),
  ('/implantations/toulouse/haute-garonne/','Maintenance industrielle Haute-Garonne (31) | Migen','Maintenance industrielle Haute-Garonne : sous-traitance aéronautique, métallurgie, agroalimentaire. Hub de techniciens à Toulouse, rappel dans l''heure.'),
  ('/lp/','Devis maintenance industrielle, migen','Techniciens de maintenance qualifiés en renfort sur votre site, ponctuel ou dans la durée. Un expert vous rappelle sous 2 h ouvrées.'),
  ('/mentions-legales/','Mentions légales, migen','Informations légales, éditeur, hébergeur et propriété intellectuelle du site migen.'),
  ('/modeles/article/','Modèle article, migen','Gabarit d''article éditorial du centre de ressources migen.'),
  ('/modeles/departement/','Modèle département, migen','Gabarit de page département : présence et interventions de migen sur un département.'),
  ('/modeles/domaine/','Modèle domaine, migen','Gabarit de page domaine : présentation d''un domaine d''expertise technique.'),
  ('/modeles/metier/','Modèle métier, migen','Gabarit de page métier : présentation d''un métier de la maintenance industrielle.'),
  ('/modeles/realisation/','Modèle réalisation, migen','Gabarit de fiche réalisation : présentation d''un chantier ou projet mené par migen.'),
  ('/modeles/ressource/','Modèle ressource, migen','Gabarit de fiche ressource (métier, technique ou pratique) du centre de ressources migen.'),
  ('/modeles/secteur/','Modèle secteur, migen','Gabarit de page secteur : présentation d''un secteur industriel accompagné par migen.'),
  ('/modeles/service-ville/','Modèle service + ville, migen','Gabarit de page programmatique croisant un service de maintenance et une ville d''intervention.'),
  ('/nous-connaitre/','Nous connaître, migen','Un seul métier : technicien de maintenance. Découvrez qui nous sommes, notre histoire et notre façon de travailler.'),
  ('/offres/','Entreprise maintenance industrielle | Migen','Entreprise maintenance industrielle : cinq façons de nous confier votre maintenance, avec des techniciens évalués, 10 % des candidats retenus.'),
  ('/offres/arret-technique/','Arrêt technique maintenance | Migen','Arrêt technique maintenance : préparation, coordination et travaux réalisés par des équipes complètes, partout en France. Rappel dans l''heure.'),
  ('/offres/audit-conseil-maintenance/','Audit et conseil en maintenance | Migen','Conseil en maintenance industrielle : audit de site, plan d''actions chiffré et priorisé. Diagnostic gratuit, rappel dans l''heure au 04 78 33 72 05.'),
  ('/offres/bureau-etudes/','Bureau d''études mécanique | Migen','Bureau d''études mécanique : conception, calculs, simulation et suivi de réalisation par une équipe d''ingénierie intégrée. Rappel dans l''heure.'),
  ('/offres/chantier/','Transfert industriel | Migen','Transfert industriel : audit, démontage, transport, remontage et remise en service partout en France. Décrivez votre projet, nous rappelons dans l''heure.'),
  ('/offres/chantier/demenagement-machines/','Déménager vos machines de production | Migen','Déménagement de machines industrielles : démontage, emballage, transport, remontage et remise en service. Rappel dans l''heure au 04 78 33 72 05.'),
  ('/offres/chantier/transfert-de-production/','Déplacer une ligne ou une usine | Migen','Transfert de production : audit, phasage, démontage, remontage et redémarrage de vos lignes sur le nouveau site. Rappel dans l''heure au 04 78 33 72 05.'),
  ('/offres/construction/','Montage industriel | Migen','Montage industriel : installation de machines et de lignes complètes, de l''ingénierie à la mise en service, partout en France. Rappel dans l''heure.'),
  ('/offres/depannage-industriel/','Dépannage industriel en urgence sur machine | Migen','Dépannage industriel partout en France : astreinte 24/24 et 7/7, techniciens évalués. Décrivez la panne, nous rappelons dans l''heure.'),
  ('/offres/depannage-industriel/astreinte/','Astreinte industrielle 24h/24 | Migen','Astreinte maintenance : Astreinte de maintenance 24/24 et 7/7 partout en France. Un numéro, un technicien évalué, un compte rendu à chaque déclenchement.'),
  ('/offres/depannage-industriel/panne-machine/','Machine à l''arrêt : qui appeler | Migen','Panne machine industrielle : ne forcez pas le redémarrage. Technicien évalué mobilisé partout en France, astreinte 24/24 et 7/7. Rappel dans l''heure.'),
  ('/offres/maintenance-externalisee/','Externaliser sa maintenance industrielle de A à Z | Migen','Maintenance industrielle externalisée de A à Z : préventif, dépannage, pièces posées, GMAO tenue. Techniciens salariés évalués, rappel dans l''heure.'),
  ('/offres/residence/','Sous-traitance maintenance | Migen','Sous-traitance maintenance : des techniciens qualifiés intégrés sur votre site, sans charge de recrutement. Sélection exigeante, rappel dans l''heure.'),
  ('/offres/residence/cahier-des-charges/','Trame de consultation maintenance | Migen','Cahier des charges maintenance : la trame en 8 sections, la méthode de rédaction, la grille d''évaluation des offres.'),
  ('/offres/residence/prestataire-ou-salarie/','Embaucher ou sous-traiter sa maintenance | Migen','Prestataire ou salarié : le comparatif honnête, coût complet, souplesse, risque de requalification. Et les cas où embaucher reste le bon choix.'),
  ('/offres/residence/recruter-un-technicien/','Recruter un technicien de maintenance | Migen','Recruter un technicien de maintenance : besoin, annonce, canaux, évaluation, fidélisation. La méthode complète, et l''alternative du technicien intégré.'),
  ('/offres/retrofit/','Moderniser une machine plutôt que la remplacer | Migen','Retrofit machine industrielle : diagnostic, rénovation mécanique, électrique et automatisme, essais et remise en service. Rappel dans l''heure, 04 78 33 72 05.'),
  ('/offres/retrofit/mise-en-conformite-machine/','Mise en conformité des machines | Migen','Mise en conformité machine : audit du parc, analyse de risques, travaux et dossier technique. Rappel dans l''heure, astreinte 24/24 au 04 78 33 72 05.'),
  ('/offres/retrofit/remise-en-etat/','Redonner sa performance à une machine usée | Migen','Remise en état machine industrielle : expertise écrite, démontage, réparation, protections, essais et rapport. Rappel dans l''heure au 04 78 33 72 05.'),
  ('/offres/zero-arret/','Contrat de maintenance | Migen','Contrat de maintenance : Un abonnement à prix fixe plutôt que des dépannages subis. Comparez le coût réel sur 12 mois.'),
  ('/partenaires/','Partenaires, migen','Nos offres en partenariat, 100 % Made in France : GMAO, intralogistique et prestations connexes.'),
  ('/preuves/','Nos preuves, migen','Ce que nous avons livré, chez qui, et en combien de temps : des chantiers datés, dans tous les secteurs.'),
  ('/preuves/aktid-centre-logistique/','Cas AKTID : montage livré en 6 semaines | Migen','Montage du centre logistique AKTID à Clermont-Ferrand : 12 monteurs mécaniciens, 8 engins de levage, six semaines de chantier et une livraison dans les temps.'),
  ('/preuves/alstef-group/','Cas ALSTEF Group : contrôle de chantier | Migen','ALSTEF Group renforce son contrôle de chantier avec Migen : techniciens autonomes intégrés aux équipes projet pour sécuriser les phases critiques.'),
  ('/preuves/amazon-centre-logistique/','Cas AMAZON ORY4 : le préventif tenu | Migen','AMAZON ORY4, centre logistique en service sans interruption : 10 à 20 techniciens Migen une semaine sur deux, par créneaux de 8 heures, depuis 2022.'),
  ('/preuves/amazon-nouveau-site/','Cas AMAZON ETZ 2 Metz : deuxième site | Migen','AMAZON confie un deuxième centre logistique à Migen : ETZ 2 à Metz, 10 techniciens polyvalents une semaine par mois, par créneaux de 8 heures.'),
  ('/preuves/autoliv/','Cas AUTOLIV : un technicien sur le parc | Migen','AUTOLIV renforce son équipe technique avec Migen : un technicien de maintenance polyvalent dédié au maintien opérationnel du parc machines, en 2025.'),
  ('/preuves/danone-lignes-de-production/','Cas DANONE Blédina : deux techniciens en 3x8 | Migen','DANONE Blédina, site de Steenvoorde : deux techniciens Migen intégrés en 3x8 sur les lignes liquides et le conditionnement poudre. Contexte et dispositif.'),
  ('/preuves/eaton-mise-en-production/','Cas EATON : 6 techniciens sur un démarrage | Migen','EATON confie à Migen l''accompagnement d''un nouveau parc machine sur son site automobile : 6 techniciens multidisciplinaires, de la livraison à la production.'),
  ('/preuves/eiffage/','EIFFAGE : préventif sur une centrale solaire | Migen','Eiffage sélectionne Migen pour renforcer ses équipes sur un chantier photovoltaïque de grande envergure : trois techniciens en maintenance préventive, 2024.'),
  ('/preuves/eriks/','ERIKS : zéro interruption critique | Migen','ERIKS confie à Migen le pilotage de son service maintenance pendant une montée de cadence et une transition d''équipe. Zéro interruption critique, T3 2025.'),
  ('/preuves/fdj/','FDJ : un technicien en continu sur site | Migen','La Française des Jeux renforce sa maintenance avec un technicien Migen affecté en continu : préventif, curatif et diagnostic sur les lignes de production.'),
  ('/preuves/gls-maintenance-curative/','Cas GLS : deux techniciens en poste | Migen','GLS confie à Migen le maintien opérationnel de ses équipements : deux techniciens sur site, dédiés au curatif des convoyeurs, trieurs et packaging automatisé.'),
  ('/preuves/groupe-atlantic/','GROUPE ATLANTIC : renfort permanent | Migen','Le Groupe Atlantic renforce ses équipes de maintenance avec 1 à 3 techniciens Migen sur ses sites de production, en présence permanente depuis octobre 2024.'),
  ('/preuves/joint-lyonnais/','JOINT LYONNAIS : réparer plutôt que racheter | Migen','Joint Lyonnais fait appel à Migen pour des défaillances qui bloquaient sa production à Lyon : diagnostic sur site et solutions calées sur son budget.'),
  ('/preuves/jtekt/','Cas JTEKT : équipements critiques tenus | Migen','JTEKT, équipementier automobile : des techniciens Migen intégrés en 2025 pour la surveillance et le curatif des équipements critiques de ses sites.'),
  ('/preuves/mccain-belgique/','Cas McCAIN : premier contrat en Belgique | Migen','McCAIN en Belgique : premier contrat Migen hors de France depuis octobre 2024, un à trois techniciens en renfort sur un site agroalimentaire à grande échelle.'),
  ('/preuves/mersen/','MERSEN : un automaticien SIEMENS dédié | Migen','MERSEN confie à Migen l''affectation d''un automaticien SIEMENS à temps plein pour sécuriser le démarrage d''une nouvelle ligne de production, en 2025.'),
  ('/preuves/ogf-arret-estival/','OGF : la maintenance tenue tout l''été | Migen','OGF renforce son équipe maintenance avec un technicien Migen pendant l''arrêt estival 2025 : équipements critiques disponibles, remise en route sans retard.'),
  ('/preuves/orthus-ecocem/','ORTHUS x ECOCEM : un site R&D construit | Migen','Ecocem confie à Orthus, filiale du groupe Migen, la construction complète de son nouveau site industriel de R&#38;D près de Paris, livraison prévue fin 2025.'),
  ('/preuves/orthus-washtec/','ORTHUS x WASHTEC : montage national | Migen','WashTec confie à Orthus, filiale du groupe Migen, le montage complet de ses portiques de lavage partout en France : réception, assemblage, raccordements.'),
  ('/preuves/soprema/','SOPREMA : montages et transferts tenus | Migen','SOPREMA confie à Migen des chantiers de montage, des déplacements de machines et du renfort technique ponctuel : délais de chantier tenus, sans pénalité.'),
  ('/preuves/stellantis-fonderie-sept-fons/','Fonderie de Sept-Fons tenue 7j/7 | Migen','STELLANTIS confie à Migen la maintenance préventive et curative de sa fonderie et de son usinage à Dompierre-sur-Besbre. Reprise en 8 semaines, 6 techniciens.'),
  ('/preuves/stellantis-grand-est/','Cas STELLANTIS Grand Est : 18 à 25 techniciens | Migen','STELLANTIS Grand Est : 18 à 25 techniciens Migen sur plusieurs sites depuis juin 2023, pendant la transition des usines vers le véhicule électrique.'),
  ('/preuves/suez-remise-en-etat/','SUEZ IWT : un renfort habilité RC1 | Migen','SUEZ IWT confie à Migen le renfort d''un site de traitement des eaux industrielles : un électromécanicien habilité risque chimique, mission de 6 mois.'),
  ('/preuves/timescope/','TIMESCOPE : maintenance de casques VR | Migen','Timescope confie à Migen la maintenance sous contrat de ses casques de réalité virtuelle déployés en France : étanchéité, réglages et fiabilité.'),
  ('/preuves/valeo-usines/','Cas VALEO : la montée en cadence tenue | Migen','VALEO : 3 à 5 techniciens Migen déployés depuis septembre 2024 pour accompagner la montée en cadence de plusieurs usines françaises. Contexte et dispositif.'),
  ('/preuves/veepee-sites-lyon/','Cas VEEPEE : contrat repris en un mois | Migen','VEEPEE confie à Migen la maintenance préventive annuelle de ses sites lyonnais : 6 techniciens en permanence, reprise de l''ensemble des sites en un mois.'),
  ('/preuves/voit-grand-est/','Cas VOIT : usinage, presses et CN tenus | Migen','VOIT intègre un technicien Migen à temps plein sur son site : maintenance des centres d''usinage, dépannage des presses et diagnostic sur commandes numériques.'),
  ('/preuves/vpk/','VPK : temps d''arrêt réduits sur le parc | Migen','VPK, papier et emballage, intègre un technicien polyvalent Migen sur son parc machines en forte cadence. Charge mieux répartie, temps d''arrêt réduits.'),
  ('/realisations/','Nos réalisations, migen','Nos références clients : SUEZ, DANONE, JTEKT, GLS et d''autres projets industriels menés à terme.'),
  ('/ressources/','Guide maintenance industrielle | Migen','Guide maintenance industrielle : nos guides et fiches pratiques de maintenance industrielle, écrits par nos techniciens.'),
  ('/ressources/articles/','Articles de maintenance industrielle | Migen','Nos articles de maintenance industrielle : stratégie, organisation, GMAO, coûts. Des guides écrits par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/cout-arret-de-production/','Coût d''un arrêt de production | Migen','Coût d''un arrêt de production : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/digitalisation-maintenance/','Digitalisation maintenance : le guide complet | Migen','Digitalisation maintenance : définition, méthode pas à pas, exemple concret et erreurs à éviter, par des techniciens qui interviennent chaque jour.'),
  ('/ressources/articles/gestion-des-dechets/','Gestion des déchets industriels | Migen','Gestion des déchets industriels : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/gmao/','Gestion de maintenance assistée par ordinateur | Migen','Gestion de maintenance assistée par ordinateur : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/ia-maintenance/','IA maintenance : usages réels en usine | Migen','IA maintenance : définition, cas d''usage vérifiés, limites et méthode pour démarrer, par une équipe qui intervient chaque jour en usine.'),
  ('/ressources/articles/maintenance-4-0/','Maintenance 4.0 | Migen','Maintenance 4.0 : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/optimiser-la-maintenance/','Optimisation de la maintenance | Migen','Optimisation de la maintenance : définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/organiser-service-maintenance/','Comment organiser un service de maintenance | Migen','Comment organiser un service de maintenance : définition, méthode en six étapes et exemple concret, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/plan-de-maintenance/','Plan de maintenance | Migen','Plan de maintenance : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/planification-maintenance/','Planning de maintenance | Migen','Planning de maintenance : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/predictive-ou-corrective/','Maintenance prédictive ou corrective | Migen','Maintenance prédictive ou corrective : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/preventive-ou-corrective/','Maintenance préventive et corrective | Migen','Maintenance préventive et corrective : définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/robot-spot/','Robot Spot en inspection industrielle | Migen','Robot spot : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/articles/suivi-de-la-maintenance/','Suivi de la maintenance : méthode et outils | Migen','Suivi de la maintenance : définition, méthode, indicateurs et exemples concrets, par des techniciens qui interviennent tous les jours en usine.'),
  ('/ressources/articles/tpm/','TPM maintenance productive totale : la méthode | Migen','TPM maintenance productive totale : définition, 8 piliers, mise en œuvre et exemple terrain, expliqués par des techniciens de maintenance industrielle.'),
  ('/ressources/fiches-pratiques/','Fiches pratiques de maintenance industrielle | Migen','Fiches pratiques de maintenance : consignation électrique, plan de prévention, permis de feu, sécurité, 5S. Des procédures écrites par nos techniciens.'),
  ('/ressources/fiches-pratiques/5s/','5S industrie | Migen','5s industrie : définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/fiches-pratiques/consignation-electrique/','Consignation électrique | Migen','Consignation électrique : définition, étapes de la norme NF C 18-510, habilitations et erreurs à éviter, par des techniciens qui la pratiquent chaque jour.'),
  ('/ressources/fiches-pratiques/permis-de-feu/','Permis de feu | Migen','Permis de feu : définition, cas obligatoires, rédaction en trois temps, contenu type et pièges à éviter avant vos travaux par points chauds.'),
  ('/ressources/fiches-pratiques/plan-de-prevention/','Plan de prévention : obligations et contenu | Migen','Plan de prévention : quand il est obligatoire, ce qu''il contient, qui le signe. La fiche pratique d''une entreprise extérieure qui en signe chaque semaine.'),
  ('/ressources/fiches-pratiques/securite-maintenance/','Sécurité maintenance industrielle | Migen','Sécurité maintenance industrielle : définition, méthode, exemple et erreurs à éviter, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/fiches-techniques/','Fiches techniques de maintenance industrielle | Migen','Fiches techniques de maintenance : TRS, MTBF, AMDEC, analyse vibratoire, GMAO. Les chiffres et les seuils, expliqués par des techniciens.'),
  ('/ressources/fiches-techniques/amdec/','Amdec | Migen','Amdec : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/fiches-techniques/analyse-vibratoire/','Analyse vibratoire | Migen','Analyse vibratoire : définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/fiches-techniques/automates-siemens/','Automate Siemens | Migen','Automate Siemens : définition, gammes SIMATIC, TIA Portal, diagnostic et obsolescence, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/fiches-techniques/cahier-des-charges-gmao/','Cahier des charges gmao | Migen','Cahier des charges gmao : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/fiches-techniques/indicateurs-maintenance/','Indicateur maintenance | Migen','Indicateur maintenance : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/fiches-techniques/mtbf-mttr/','Mtbf | Migen','Mtbf : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/fiches-techniques/niveaux-de-maintenance/','Niveaux de maintenance | Migen','Niveaux de maintenance : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/fiches-techniques/outils-de-diagnostic/','Outils de diagnostic maintenance | Migen','Outils de diagnostic maintenance : définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/fiches-techniques/trs/','TRS : calculer et améliorer votre rendement | Migen','TRS : définition, formule de calcul, exemple chiffré et erreurs à éviter. La fiche technique écrite avec des techniciens qui voient des lignes tous les jours.'),
  ('/ressources/livres-blancs/','Livres blancs maintenance industrielle | Migen','Nos livres blancs de maintenance industrielle : des dossiers de décision à emporter, écrits par des techniciens qui interviennent tous les jours.'),
  ('/ressources/livres-blancs/externaliser-sa-maintenance/','Externaliser sa maintenance | Migen','Externaliser sa maintenance sans perdre la main : la méthode, les garde-fous et les pièges, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/livres-blancs/retrofit-ou-remplacement/','Retrofit ou remplacement | Migen','Retrofit ou remplacement : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/process/','Process de maintenance industrielle | Migen','Nos process de maintenance industrielle : préventif, sélection des techniciens, arrêt technique, sécurité. Les méthodes de terrain, expliquées.'),
  ('/ressources/process/gestion-maintenance-preventive/','Gestion de la maintenance préventive | Migen','Gestion de la maintenance préventive : définition, méthode pas à pas, exemple concret et erreurs à éviter, par des techniciens de terrain.'),
  ('/ressources/process/preparer-un-arret-technique/','Préparation arrêt technique | Migen','Préparation arrêt technique : définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/process/protocole-de-securite/','Protocole de sécurité | Migen','Protocole de sécurité : Définition, méthode et exemples concrets, par des techniciens qui interviennent tous les jours.'),
  ('/ressources/process/selection-des-techniciens/','Sélection technicien de maintenance | Migen','Sélection technicien de maintenance : la méthode Migen, entretien technique et comportemental, 10 % des candidats retenus, résultats partagés.'),
  ('/rse/','Engagements RSE, migen','Nos engagements sociaux et environnementaux : emploi durable, sobriété et ancrage territorial.'),
  ('/secteurs/','Maintenance industrielle par secteur | Migen','Maintenance usine : des techniciens affectés selon l''expérience de votre secteur, pas au hasard. 10 % des candidats retenus, 4 agences en France.'),
  ('/secteurs/aeronautique/','Maintenance des moyens de production aéro | Migen','Maintenance industrie aéronautique : machines 5 axes, moyens de mesure, montée en cadence. Traçabilité prête pour l''audit client. 4 agences en France.'),
  ('/secteurs/agroalimentaire/','Maintenance industrielle en agroalimentaire | Migen','Maintenance agroalimentaire : lavage quotidien, ateliers à 4 °C, traçabilité auditée. Des techniciens formés à vos contraintes. DANONE, McCAIN.'),
  ('/secteurs/automobile/','Maintenance de lignes automobiles | Migen','Maintenance industrie automobile : takt time, cellules robotisées, changement de série, électrification. STELLANTIS, VALEO, JTEKT, AUTOLIV, EATON.'),
  ('/secteurs/chimie/','Maintenance de site chimique classé | Migen','Maintenance industrie chimique : permis de travail, consignations, zones ATEX, procédés continus. Techniciens formés avant l''accès. SUEZ, MERSEN.'),
  ('/secteurs/industrie-lourde/','Maintenance de fours, presses et broyeurs | Migen','Maintenance industrie lourde : fours, presses de forge, broyeurs, ponts roulants. Préparation type chantier, techniciens confirmés. STELLANTIS, MERSEN.'),
  ('/secteurs/industrie-metallique/','Maintenance d''atelier usinage et tôlerie | Migen','Maintenance industrie métallique : broches, glissières, presses, robots de soudure, poussière métallique. Contrôles géométriques tracés. VOIT, MERSEN.'),
  ('/secteurs/logistique/','Maintenance entrepôt et convoyage | Migen','Maintenance équipements logistiques : convoyeurs, tri, quais, transstockeurs. Disponibilité mesurée, astreinte réelle. AMAZON, GLS, VEEPEE.'),
  ('/secteurs/logistique/maintenance-convoyeur/','Entretien et dépannage de convoyeurs | Migen','Maintenance convoyeur : bandes, rouleaux, chaînes, trieurs. Préventif mesuré, dépannage outillé, astreinte 24/24 et 7/7. AMAZON, GLS, VEEPEE.'),
  ('/secteurs/logistique/peak-season/','Préparer vos équipements avant le pic | Migen','Peak season logistique : revue technique à J-90, pièces à J-60, renforts briefés à J-30. Astreinte réelle pendant la vague. AMAZON, VEEPEE, GLS.'),
  ('/secteurs/menuiserie-industrielle/','Maintenance de machines à bois | Migen','Maintenance menuiserie industrielle : scies à panneaux, centres d''usinage bois, plaqueuses, aspiration. Le suivi que vos machines n''ont jamais eu.'),
  ('/secteurs/nucleaire/','Maintenance conventionnelle en site nucléaire | Migen','Maintenance nucléaire : utilités, machines tournantes et équipements conventionnels des sites de la filière. Préparation écrite, traçabilité totale.'),
  ('/secteurs/pharmaceutique/','Maintenance de site pharmaceutique BPF | Migen','Maintenance pharmaceutique : techniciens formés aux BPF et au comportement en ZAC, circuit de requalification défini avec votre assurance qualité.'),
  ('/travaux-industriels/','Travaux industriels en France | Migen','Travaux industriels : transfert, démantèlement, montage, levage et manutention lourde partout en France. Rappel dans l''heure au 04 78 33 72 05.'),
  ('/travaux-industriels/demantelement-industriel/','Démantèlement industriel de site et d''équipements | Migen','Démantèlement industriel : dépose d''équipements, démontage pour valorisation ou transfert, traçabilité des déchets. Rappel dans l''heure au 04 78 33 72 05.'),
  ('/travaux-industriels/levage-manutention/','Levage industriel et manutention de charges | Migen','Manutention lourde et levage industriel : élingage, mise en position et déplacement de machines en atelier. Rappel dans l''heure au 04 78 33 72 05.'),
  ('/travaux-industriels/montage-industriel/','Montage industriel et implantation de lignes | Migen','Montage industriel : assemblage, calage, raccordements et essais de vos lignes de production partout en France. Rappel dans l''heure au 04 78 33 72 05.'),
  ('/travaux-industriels/transfert-industriel/','Transfert industriel et déménagement d''usine | Migen','Transfert industriel : déménagement d''usine, de machines industrielles et de lignes de production partout en France. Rappel dans l''heure au 04 78 33 72 05.'),
  ('/valeurs/','Nos valeurs, migen','Les valeurs qui guident notre métier de technicien de maintenance au quotidien.')
) as v(pa, t, d) join pages p on p.path = v.pa
on conflict (page_id) do nothing;

commit;