-- Un mot clé principal par page, repris du frontmatter du corpus.
-- Les pages de preuve et les hubs n'en portent pas : la règle « un mot clé
-- principal par page » ne s'applique qu'aux pages qui ciblent une requête.
update pages p set mot_cle_principal = v.mc
  from (values
  ('/carriere/','migen recrutement'),
  ('/carriere/agent-de-maintenance/','agent de maintenance industrielle'),
  ('/carriere/alternance/','alternance maintenance industrielle'),
  ('/carriere/automaticien/','automaticien'),
  ('/carriere/automaticien/salaire/','salaire automaticien'),
  ('/carriere/electromecanicien/','electromecanicien'),
  ('/carriere/electromecanicien/competences/','compétences électromécanicien'),
  ('/carriere/electromecanicien/salaire/','salaire électromécanicien'),
  ('/carriere/responsable-maintenance/','responsable maintenance'),
  ('/carriere/roboticien/','roboticien'),
  ('/carriere/technicien-de-maintenance/','technicien de maintenance'),
  ('/carriere/technicien-de-maintenance/formation/','formation technicien de maintenance'),
  ('/carriere/technicien-de-maintenance/salaire/','salaire technicien de maintenance'),
  ('/carriere/technicien-itinerant/','technicien de maintenance itinérant'),
  ('/expertises/','maintenance des équipements industriels'),
  ('/expertises/automatisme/','automatisme industriel'),
  ('/expertises/automatisme/programmation-automate/','programmation automate'),
  ('/expertises/automatisme/schneider/','automate schneider'),
  ('/expertises/automatisme/siemens/','automaticien siemens'),
  ('/expertises/electrique/','maintenance électrique industrielle'),
  ('/expertises/electromecanique/','électromécanique industrielle'),
  ('/expertises/hydraulique/','maintenance hydraulique'),
  ('/expertises/hydraulique/verin-hydraulique/','réparation vérin hydraulique'),
  ('/expertises/mecanique/','maintenance mécanique'),
  ('/expertises/mecanique/lubrification/','lubrification industrielle'),
  ('/expertises/mecanique/machine-outil/','maintenance machine outil'),
  ('/expertises/pneumatique/','maintenance pneumatique'),
  ('/expertises/robotique/','maintenance robotique'),
  ('/expertises/robotique/abb/','abb robotique'),
  ('/expertises/robotique/fanuc/','fanuc robotique'),
  ('/expertises/robotique/integrateur-robotique/','intégrateur robotique'),
  ('/expertises/soudure/','soudure industrielle'),
  ('/expertises/specialisations-constructeur/','automaticien industriel'),
  ('/expertises/tuyauterie/','maintenance tuyauterie industrielle'),
  ('/expertises/tuyauterie/nettoyage/','nettoyage tuyauterie industrielle'),
  ('/expertises/types-de-maintenance/','types de maintenance'),
  ('/expertises/types-de-maintenance/maintenance-ameliorative/','maintenance améliorative'),
  ('/expertises/types-de-maintenance/maintenance-conditionnelle/','maintenance conditionnelle'),
  ('/expertises/types-de-maintenance/maintenance-corrective/','maintenance corrective'),
  ('/expertises/types-de-maintenance/maintenance-curative/','maintenance curative'),
  ('/expertises/types-de-maintenance/maintenance-palliative/','maintenance palliative'),
  ('/expertises/types-de-maintenance/maintenance-predictive/','maintenance prédictive'),
  ('/expertises/types-de-maintenance/maintenance-preventive/','maintenance préventive'),
  ('/expertises/types-de-maintenance/maintenance-previsionnelle/','maintenance prévisionnelle'),
  ('/expertises/types-de-maintenance/preventive-systematique/','maintenance préventive systématique'),
  ('/implantations/','maintenance industrielle france'),
  ('/implantations/lille/','maintenance industrielle lille'),
  ('/implantations/lyon/','maintenance industrielle lyon'),
  ('/implantations/lyon/grenoble/','maintenance industrielle grenoble'),
  ('/implantations/lyon/haute-savoie/','maintenance industrielle haute savoie'),
  ('/implantations/lyon/rhone/','maintenance industrielle rhône'),
  ('/implantations/lyon/saint-etienne/','maintenance industrielle saint etienne'),
  ('/implantations/lyon/valence/','maintenance industrielle valence'),
  ('/implantations/maintenance-industrielle-avignon/','maintenance industrielle avignon'),
  ('/implantations/maintenance-industrielle-besancon/','maintenance industrielle besançon'),
  ('/implantations/maintenance-industrielle-caen/','maintenance industrielle caen'),
  ('/implantations/maintenance-industrielle-clermont-ferrand/','maintenance industrielle clermont-ferrand'),
  ('/implantations/maintenance-industrielle-dijon/','maintenance industrielle dijon'),
  ('/implantations/maintenance-industrielle-dunkerque/','maintenance industrielle dunkerque'),
  ('/implantations/maintenance-industrielle-le-havre/','maintenance industrielle le havre'),
  ('/implantations/maintenance-industrielle-le-mans/','maintenance industrielle le mans'),
  ('/implantations/maintenance-industrielle-limoges/','maintenance industrielle limoges'),
  ('/implantations/maintenance-industrielle-marseille/','maintenance industrielle marseille'),
  ('/implantations/maintenance-industrielle-metz/','maintenance industrielle metz'),
  ('/implantations/maintenance-industrielle-montpellier/','maintenance industrielle montpellier'),
  ('/implantations/maintenance-industrielle-nice/','maintenance industrielle nice'),
  ('/implantations/maintenance-industrielle-orleans/','maintenance industrielle orleans'),
  ('/implantations/maintenance-industrielle-pau/','maintenance industrielle pau'),
  ('/implantations/maintenance-industrielle-poitiers/','maintenance industrielle poitiers'),
  ('/implantations/maintenance-industrielle-reims/','maintenance industrielle reims'),
  ('/implantations/maintenance-industrielle-tours/','maintenance industrielle tours'),
  ('/implantations/maintenance-industrielle-troyes/','maintenance industrielle troyes'),
  ('/implantations/maintenance-industrielle-valenciennes/','maintenance industrielle valenciennes'),
  ('/implantations/nantes/','maintenance industrielle nantes'),
  ('/implantations/nantes/brest/','maintenance industrielle brest'),
  ('/implantations/nantes/loire-atlantique/','maintenance industrielle loire atlantique'),
  ('/implantations/nantes/rennes/','maintenance industrielle rennes'),
  ('/implantations/paris/','maintenance industrielle paris'),
  ('/implantations/paris/essonne/','maintenance industrielle essonne'),
  ('/implantations/paris/rouen/','maintenance industrielle rouen'),
  ('/implantations/strasbourg/','maintenance industrielle strasbourg'),
  ('/implantations/strasbourg/alsace/','maintenance industrielle alsace'),
  ('/implantations/strasbourg/mulhouse/','maintenance industrielle mulhouse'),
  ('/implantations/toulouse/','maintenance industrielle toulouse'),
  ('/implantations/toulouse/bordeaux/','maintenance industrielle bordeaux'),
  ('/implantations/toulouse/charente/','maintenance industrielle charente'),
  ('/implantations/toulouse/gironde/','maintenance industrielle gironde'),
  ('/implantations/toulouse/haute-garonne/','maintenance industrielle haute garonne'),
  ('/offres/','entreprise maintenance industrielle'),
  ('/offres/arret-technique/','arrêt technique maintenance'),
  ('/offres/audit-conseil-maintenance/','conseil en maintenance industrielle'),
  ('/offres/bureau-etudes/','bureau d''études mécanique'),
  ('/offres/chantier/','transfert industriel'),
  ('/offres/chantier/demenagement-machines/','déménagement de machines industrielles'),
  ('/offres/chantier/transfert-de-production/','transfert de production'),
  ('/offres/construction/','montage industriel'),
  ('/offres/depannage-industriel/','dépannage industriel'),
  ('/offres/depannage-industriel/astreinte/','astreinte maintenance'),
  ('/offres/depannage-industriel/panne-machine/','panne machine industrielle'),
  ('/offres/residence/','sous-traitance maintenance'),
  ('/offres/residence/cahier-des-charges/','cahier des charges maintenance'),
  ('/offres/residence/prestataire-ou-salarie/','prestataire ou salarié'),
  ('/offres/residence/recruter-un-technicien/','recruter un technicien de maintenance'),
  ('/offres/retrofit/','retrofit machine industrielle'),
  ('/offres/retrofit/mise-en-conformite-machine/','mise en conformité machine'),
  ('/offres/retrofit/remise-en-etat/','remise en état machine industrielle'),
  ('/offres/zero-arret/','contrat de maintenance'),
  ('/ressources/','guide maintenance industrielle'),
  ('/ressources/articles/cout-arret-de-production/','coût d''un arrêt de production'),
  ('/ressources/articles/digitalisation-maintenance/','digitalisation maintenance'),
  ('/ressources/articles/gestion-des-dechets/','gestion des déchets industriels'),
  ('/ressources/articles/gmao/','gestion de maintenance assistée par ordinateur'),
  ('/ressources/articles/ia-maintenance/','ia maintenance'),
  ('/ressources/articles/maintenance-4-0/','maintenance 4.0'),
  ('/ressources/articles/optimiser-la-maintenance/','optimisation de la maintenance'),
  ('/ressources/articles/organiser-service-maintenance/','comment organiser un service de maintenance'),
  ('/ressources/articles/plan-de-maintenance/','plan de maintenance'),
  ('/ressources/articles/planification-maintenance/','planning de maintenance'),
  ('/ressources/articles/predictive-ou-corrective/','maintenance prédictive ou corrective'),
  ('/ressources/articles/preventive-ou-corrective/','maintenance préventive et corrective'),
  ('/ressources/articles/robot-spot/','robot spot'),
  ('/ressources/articles/suivi-de-la-maintenance/','suivi de la maintenance'),
  ('/ressources/articles/tpm/','tpm maintenance'),
  ('/ressources/fiches-pratiques/5s/','5s industrie'),
  ('/ressources/fiches-pratiques/consignation-electrique/','consignation électrique'),
  ('/ressources/fiches-pratiques/permis-de-feu/','permis de feu'),
  ('/ressources/fiches-pratiques/plan-de-prevention/','plan de prévention'),
  ('/ressources/fiches-pratiques/securite-maintenance/','sécurité maintenance industrielle'),
  ('/ressources/fiches-techniques/amdec/','amdec'),
  ('/ressources/fiches-techniques/analyse-vibratoire/','analyse vibratoire'),
  ('/ressources/fiches-techniques/automates-siemens/','automate siemens'),
  ('/ressources/fiches-techniques/cahier-des-charges-gmao/','cahier des charges gmao'),
  ('/ressources/fiches-techniques/indicateurs-maintenance/','indicateur maintenance'),
  ('/ressources/fiches-techniques/mtbf-mttr/','mtbf'),
  ('/ressources/fiches-techniques/niveaux-de-maintenance/','niveaux de maintenance'),
  ('/ressources/fiches-techniques/outils-de-diagnostic/','outils de diagnostic maintenance'),
  ('/ressources/fiches-techniques/trs/','trs'),
  ('/ressources/livres-blancs/retrofit-ou-remplacement/','retrofit ou remplacement'),
  ('/ressources/process/gestion-maintenance-preventive/','gestion de la maintenance préventive'),
  ('/ressources/process/preparer-un-arret-technique/','préparation arrêt technique'),
  ('/ressources/process/protocole-de-securite/','protocole de sécurité'),
  ('/ressources/process/selection-des-techniciens/','sélection technicien de maintenance'),
  ('/secteurs/','maintenance usine'),
  ('/secteurs/aeronautique/','maintenance industrie aéronautique'),
  ('/secteurs/agroalimentaire/','maintenance agroalimentaire'),
  ('/secteurs/automobile/','maintenance industrie automobile'),
  ('/secteurs/chimie/','maintenance industrie chimique'),
  ('/secteurs/industrie-lourde/','maintenance industrie lourde'),
  ('/secteurs/industrie-metallique/','maintenance industrie métallique'),
  ('/secteurs/logistique/','maintenance équipements logistiques'),
  ('/secteurs/logistique/maintenance-convoyeur/','maintenance convoyeur'),
  ('/secteurs/logistique/peak-season/','peak season logistique'),
  ('/secteurs/menuiserie-industrielle/','maintenance menuiserie industrielle'),
  ('/secteurs/nucleaire/','maintenance nucléaire'),
  ('/secteurs/pharmaceutique/','maintenance pharmaceutique')
  ) as v(pa, mc)
 where p.path = v.pa and p.mot_cle_principal is distinct from v.mc;
