/**
 * Le rail de logos de « Références » (sp-proof) de la page « vente » de la
 * maquette, dans son ordre : fichier sous `public/assets/clients/`, nom, et
 * `true` pour les deux logos clairs qu'elle inverse (OGF, Groupe Atlantic).
 */
export const LOGOS_REFERENCES: readonly (readonly [string, string, boolean])[] = [
  ["danone.png", "Danone", false],
  ["stellantis.png", "Stellantis", false],
  ["amazon.svg", "Amazon", false],
  ["valeo.svg", "Valeo", false],
  ["savoye.png", "Savoye", false],
  ["mccain.svg", "McCain", false],
  ["autoliv.svg", "Autoliv", false],
  ["eaton.svg", "Eaton", false],
  ["gls.svg", "GLS", false],
  ["bledina.svg", "Blédina", false],
  ["jtekt.svg", "JTEKT", false],
  ["veepee.svg", "Veepee", false],
  ["suez.svg", "Suez", false],
  ["jacquet-brossard.png", "Jacquet Brossard", false],
  ["mersen.svg", "Mersen", false],
  ["alstef.webp", "Alstef Group", false],
  ["eiffage.svg", "Eiffage", false],
  ["motherson.svg", "Motherson", false],
  ["la-panetiere.svg", "La Panetière", false],
  ["eriks.svg", "ERIKS", false],
  ["voit.svg", "Voit", false],
  ["ecocem.png", "Ecocem", false],
  ["dimomaint.svg", "DimoMaint", false],
  ["groupe-atlantic.png", "Groupe Atlantic", true],
  ["tournaire.png", "Tournaire", false],
  ["aktid.png", "Aktid", false],
  ["salaison-du-maconnais.png", "Salaisons du Mâconnais", false],
  ["vignal-systems.svg", "Vignal Systems", false],
  ["joint-lyonnais.png", "Joint Lyonnais", false],
  ["ciuch.svg", "Ciuch", false],
  ["rector-lesage.png", "Rector Lesage", false],
  ["bamesa.png", "Bamesa", false],
  ["jeld-wen.png", "Jeld-Wen", false],
  ["atena.png", "Atena", false],
  ["soprema.svg", "Soprema", false],
  ["washtec.svg", "WashTec", false],
  ["timescope.png", "Timescope", false],
  ["ogf.png", "OGF", true],
];
